### ISSUE TITLE
interval.prev(): loops infinitely in Brazilian locale

### ISSUE THREAD

**Issue by m0nzderr** [harrisiirak/cron-parser#100]
In Brazil, when it reaches the value of "2017-10-16T00:59:59.999", the operation

```
CronDate.prototype.subtractDay = function() {
  this._date.subtract(1, 'day').endOf('day');
};
```

stays at the same date, causing infinite loop.

see issue https://github.com/moment/moment/issues/3132 :

```
moment("2017-10-16T00:59:59.999").subtract(1,'day').endOf('day')
=> "2017-10-16T00:59:59.999"
```

Until the issue is not fixed, I'd suggest to add a simple workaround for it, something like detecting the "no change" situation and forcing the date to change.

**Comment by harrisiirak** [comment]
@m0nzderr thanks for reporting! Can you provide me some example(s)?

Not sure how to reproduce this one. Tried to change the local tz + changed the opts.tz: not getting the infinite loop.

Example code:

```js
const interval = parser.parseExpression('0 0 * * * *', {
  currentDate: '2017-10-16T00:59:59.999',
  tz: 'America/Sao_Paulo'
});

console.log(interval.next().toISOString());
console.log(interval.next().toISOString());
console.log(interval.prev().toISOString());
console.log(interval.next().toISOString());
```

**Comment by m0nzderr** [comment]
@harrisiirak , sorry for taking too long to respond.
Here is one of the cases that loops forever:

```
const parser = require("cron-parser")
const interval = parser.parseExpression('0 0 0 1 1 *', {
  currentDate: 1498359600000,
  tz: 'America/Sao_Paulo'
});

console.log(interval.next().toISOString());
console.log(interval.prev().toISOString()); // it gets stuck here forever around DST switch
console.log(interval.next().toISOString());
console.log(interval.next().toISOString());
```

In my production code I had to overcome this problem by overriding your methods with a hack that prevents it from getting stuck on the same date:

```
CronDate.prototype.subtractDay = function () {
    let before = this._date.date();
    this._date.subtract(1, 'day').endOf('day');
    while (this._date.date() === before) {
        this._date.subtract(1, 'h');
    }
};

CronDate.prototype.addDay = function () {
    let before = this._date.date();
    this._date.add(1, 'day').startOf('day');
    while (this._date.date() === before) {
        this._date.add(1, 'h');
    }
};
```

**Comment by santigimeno** [comment]
@m0nzderr I think your patch looks good. Could you send a PR?

**Comment by m0nzderr** [comment]
@santigimeno got it!

**Comment by harrisiirak** [comment]
@m0nzderr any updates?

**Comment by harrisiirak** [comment]
Closing this issues as there are no further updates on this.
