### ISSUE TITLE
Parsing error

### ISSUE THREAD

**Issue by sanjorgek** [harrisiirak/cron-parser#103]
When I did

```bash
> const cronstrue = require('cronstrue');
> cronstrue.toString('0 1 1 10 9 1')
'At 01:01 AM, on day 10 of the month, only on Monday, only in September'
```

I expected this string. But `cron-parser` did this

```bash
> const parser = require('cron-parser');
> let interval = parser.parseExpression('0 1 1 10 9 1')
> console.log('Date: ', interval2.next().toString());
Date:  Mon Sep 04 2017 01:01:00 GMT-0500
> console.log('Date: ', interval2.next().toString());
Date:  Sun Sep 10 2017 01:01:00 GMT-0500
```

**Comment by sanjorgek** [comment]
`cron-parser` v2.4.1
`cronstrue ` v0.10.8 
`node` v6.10.1

**Comment by santigimeno** [comment]
@sanjorgek I don't think there's an error. From [crontab manual](https://linux.die.net/man/5/crontab)

> Note: The day of a command's execution can be specified by two fields - day of month, and day of week. If both fields are restricted (ie, aren't *), the command will be run when either field matches the current time. For example,
"30 4 1,15 * 5" would cause a command to be run at 4:30 am on the 1st and 15th of each month, plus every Friday.

**Comment by harrisiirak** [comment]
@santigimeno sounds about right
