### ISSUE TITLE
Any support for quartz syntax?

### ISSUE THREAD

**Issue by rvalenciano** [harrisiirak/cron-parser#104]
Hi, any support for quartz syntax? I'm using [angular-cronjobs](https://github.com/angular-cron-jobs/angular-cron-jobs), and they support quartz syntax. I also want to validate it with this package, but it seems like quartz is not supported.

Any planned support for it in the roadmap? I could collaborate if some basic orientation is provided.

**Comment by harrisiirak** [comment]
@rvalenciano depends what you're exactly meaning but the short answer is no. Currently only the standard UNIX syntax is supported (minus special characters).
