### ISSUE TITLE
Leap years are not supported

### ISSUE THREAD

**Issue by ghostsquad** [harrisiirak/cron-parser#105]
https://github.com/harrisiirak/cron-parser/blob/master/lib/expression.js#L74

This static table of days in the month is inaccurate.

**Comment by santigimeno** [comment]
Are you sure they're not supported? See: https://github.com/harrisiirak/cron-parser/blob/master/lib/expression.js#L437-L441 (Haven't tested it though)

**Comment by ghostsquad** [comment]
oh, actually, that looks right. sorry about this.
