### ISSUE TITLE
Does not support cron of specific minute or hour with step value

### ISSUE THREAD

**Issue by legend80s** [harrisiirak/cron-parser#106]
Version: 2.4.1

Now: 9/21/2017, 11:32:37 AM

Cron: 15 50/1 11 * * *

Task Expected to be run at every minute with second 15 and hour 11 from minute 50:
9/21/2017, 11:50:15 AM
9/21/2017, 11:51:15 AM
9/21/2017, 11:52:15 AM
...

But run at 11:50:15 everyday 
Thu Sep 21 2017 11:50:15 GMT+0800
Fri Sep 22 2017 11:50:15 GMT+0800
Sat Sep 23 2017 11:50:15 GMT+0800

`test.js` Code:
```javascript
const schedule = require('node-schedule');
const parser = require('cron-parser');

const cron = process.argv.slice(2)[0];
console.log('cron:', cron)

try {
  const interval = parser.parseExpression(cron);

  console.log('Next 3 recurrences');
  console.log(interval.next().toLocaleString());
  console.log(interval.next().toLocaleString());
  console.log(interval.next().toLocaleString());
} catch (err) {
  console.log('Error: ' + err.message);
}

schedule.scheduleJob(cron, () => {
  console.log('Run Task at', new Date().toLocaleString());
});
```
Execute the code
`$ node test.js '15 50/1 11 * * *'`

**Comment by harrisiirak** [comment]
@legend80s are you very sure that your cron pattern is correct? If you want to iterate over the minutes you need to provide full range (can't predict the range here as it may be `0-50` or `50-59`).

For the example: `15 50-59/1 11 * * *`
Simplified example: `15 50-59 11 * * *`

Outputs:

```
Thu, 21 Sep 2017 08:50:15 GMT
Thu, 21 Sep 2017 08:51:15 GMT
Thu, 21 Sep 2017 08:52:15 GMT
Thu, 21 Sep 2017 08:53:15 GMT
Thu, 21 Sep 2017 08:54:15 GMT
Thu, 21 Sep 2017 08:55:15 GMT
Thu, 21 Sep 2017 08:56:15 GMT
```

Should be what are you looking for?

**Comment by harrisiirak** [comment]
@legend80s did this help you?

**Comment by legend80s** [comment]
@harrisiirak Yes, It does. Thank you very much.
