### ISSUE TITLE
Timer with 0 30 0 * * SAT-SUN not correctly parsed

### ISSUE THREAD

**Issue by basvdijk** [harrisiirak/cron-parser#107]
## Current behaviour
When it is Saturday 11:00 am and I set a cron job like:
- `0 30 0 * * SAT-SUN` result: Invalid range: 6-0
- `0 30 0 * * SAT,SUN` result: the date for the next Saturday is returned instead of tomorrow when it is Sunday

## Expected behaviour
When I set a timer with `0 30 0 * * SAT-SUN` or `0 30 0 * * SAT,SUN` I expect it to return the next matching day. In this example Sunday at 0:30h

**Comment by harrisiirak** [comment]
@basvdijk thanks for reporting! I'm going look into this I'll let you know what I find.

**Comment by harrisiirak** [comment]
Can confirm that it's related to this: https://github.com/harrisiirak/cron-parser/issues/102

**Comment by basvdijk** [comment]
Ok fair enough but #102 is not about my issue below right?

`0 30 0 * * SAT,SUN` result: the date for the next Saturday is returned instead of tomorrow when it is Sunday

**Comment by harrisiirak** [comment]
@basvdijk the first issue you mentioned with the range parsing is actually related.

Regarding your problem.

```javascript
const options = {
  currentDate: '2017-09-23T11:00:00.000Z'
};

const interval = parser.parseExpression("0 30 0 * * SAT,SUN", options);

console.log(interval.next().toDate().toUTCString());
console.log(interval.next().toDate().toUTCString());
console.log(interval.next().toDate().toUTCString());
console.log(interval.next().toDate().toUTCString());
console.log(interval.next().toDate().toUTCString());
console.log(interval.next().toDate().toUTCString());
```

The results are (my local timezone is UTC+3, so we must take this into account):

```
2017-09-23T21:30:00.000Z
2017-09-29T21:30:00.000Z
2017-09-30T21:30:00.000Z
2017-10-06T21:30:00.000Z
2017-10-07T21:30:00.000Z
2017-10-13T21:30:00.000Z
```

I'm missing something here? If yes, please provide me example code so I can provider some further help.

**Comment by basvdijk** [comment]
I tried to reproduce it:

```
const options = {
  currentDate: '2017-09-23T23:00:00.000Z'
};

const interval = parser.parseExpression("0 30 0 * * SAT,SUN", options);

console.log(interval.next().toDate().toString());
console.log(interval.next().toDate().toString());
console.log(interval.next().toDate().toString());
console.log(interval.next().toDate().toString());
console.log(interval.next().toDate().toString());
console.log(interval.next().toDate().toString());
```

Which gives:
```
2017-09-24T19:14:40.284Z
Sat Sep 30 2017 00:30:00 GMT+0200 (CEST)
Sat Oct 07 2017 00:30:00 GMT+0200 (CEST)
Sat Oct 14 2017 00:30:00 GMT+0200 (CEST)
Sat Oct 21 2017 00:30:00 GMT+0200 (CEST)
Sat Oct 28 2017 00:30:00 GMT+0200 (CEST)
Sat Nov 04 2017 00:30:00 GMT+0100 (CET)
```

Which are all Saturdays. I expect also to have Sundays in the list since 23th September is a Saturday so the next interval should be on the following Sunday according to `0 30 0 * * SAT,SUN` 

Just to be sure `0 30 0 * * SAT,SUN` means every Saturday **and** Sunday on 0:30 AM right?

**Comment by harrisiirak** [comment]
That is interesting as the same code produces:

```
Sat Sep 30 2017 00:30:00 GMT+0300 (EEST)
Sun Oct 01 2017 00:30:00 GMT+0300 (EEST)
Sat Oct 07 2017 00:30:00 GMT+0300 (EEST)
Sun Oct 08 2017 00:30:00 GMT+0300 (EEST)
Sat Oct 14 2017 00:30:00 GMT+0300 (EEST)
Sun Oct 15 2017 00:30:00 GMT+0300 (EEST)
```

But I'll investigate this a bit more when I've more time.

> Just to be sure 0 30 0 * * SAT,SUN means every Saturday and Sunday on 0:30 AM right?

Yes you're correct. https://crontab.guru/#30_0_*_*_SAT,SUN

**Comment by basvdijk** [comment]
I am using npm 5.4.2 and node 8.2.1. Tried on both osx and ubuntu (on RPI). My current timezone is CEST

**Comment by santigimeno** [comment]
@basvdijk I've tried to reproduce the issue with no luck. I'm using osx, node 8.2.1, on CEST and set the date of my computer the Sept 24th and it worked correctly:

```
2017-09-24T19:14:42.721Z
Sat Sep 30 2017 00:30:00 GMT+0200 (CEST)
Sun Oct 01 2017 00:30:00 GMT+0200 (CEST)
Sat Oct 07 2017 00:30:00 GMT+0200 (CEST)
Sun Oct 08 2017 00:30:00 GMT+0200 (CEST)
Sat Oct 14 2017 00:30:00 GMT+0200 (CEST)
Sun Oct 15 2017 00:30:00 GMT+0200 (CEST)
```

**Comment by basvdijk** [comment]
Could it have something to do with daylight saving time? The bug was reported when we still had DST

**Comment by santigimeno** [comment]
Not sure as I set the date of the computer to that specific date.

**Comment by harrisiirak** [comment]
Closing this as there isn't reproducible case.
