### ISSUE TITLE
Question about Timezone and DST support

### ISSUE THREAD

**Issue by Eric24** [harrisiirak/cron-parser#111]
I have a couple of questions about cron-parser:

1. It appears that setting the 'tz' prop only applies to the output. Wouldn't it make sense to also apply the selected timezone to the input values? This way, setting a timezone assumes all date/times are in that timezone.

2. Is DST (Daylight Saving Time) supported automatically when the 'tz' prop is set that DST is observed in that timezone?

**Comment by santigimeno** [comment]
>It appears that setting the 'tz' prop only applies to the output. Wouldn't it make sense to also apply the selected timezone to the input values? This way, setting a timezone assumes all date/times are in that timezone.

Are you sure about this? Do you have an example that demonstrates the issue? Looking at [this](https://github.com/harrisiirak/cron-parser/blob/master/lib/expression.js#L25-L27), it does not seem that way.  

> Is DST (Daylight Saving Time) supported automatically when the 'tz' prop is set that DST is observed in that timezone?

Yes, it should. If you have an example that does not work please let us know.

**Comment by Eric24** [comment]
Thanks for the quick response.

Regarding 'tz', here's what I'm seeing:

- If I don't set currentDate or endDate, it works as expected, for any 'tz' or no 'tz' (UTC default); the "now" datetime and the output datetimes are in the specified timezone.
- If I set 'tz': 'America/Chicago' (for example), the inputs for currentDate/endDate are not interpreted as being in the specified timezone. I can force a timezone by adding "GMT-0600" (for example), but if I just supply a value like 'Fri, 20 Oct 2017 12:30:00', it's interpreted as UTC (i.e. instead of 'Fri Oct 20 2017 **12:32:00** GMT-0500' being the first interval returned, I get instead 'Fri Oct 20 2017 **07:32:00** GMT-0500'). My expectation (even after looking at the code example) is that input dates should be interpreted as being in the specified 'tz', unless a timezone suffix is explicitly declared.

Regarding DST, upon further testing, I realized I was interpreting the output incorrectly. DST is working.

My test code below:
```
var options = {
  currentDate: new Date('2017-10-20 12:30:00'), //('Wed, 26 Dec 2012 12:38:53 UTC'),
  endDate: new Date('2017-10-20 13:00:00'), //('Wed, 26 Dec 2012 15:40:00 UTC'),
  tz: 'America/Chicago',
  iterator: false
};

try {
  var interval = parser.parseExpression('0 */2 * * * *', options);

  while (true) {
    try {
      var obj = interval.next();
      log.info(obj.getTime(), obj.toString());
    } catch (e) {
      break;
    }
  }
} catch (err) {
  log.error('Error: ' + err.message);
}
```

**Comment by santigimeno** [comment]
@Eric24 okay I understand now.

For the record, I think the current behavior is correct, let me explain why:

- If you pass a `Date` object to `currentDate` or `endDate` that object is already set to the TZ the system where the js engine is running on. It corresponds to an UTC value, so translating that to a different timezone won't modify this UTC value. Thus this corresponds to the `07:30:00 GMT-0500` you're observing.
- To accomplish what you want you must pass directly a string representation of the Date you want (without the TZ info of course). So this code should work for you:

```js
var options = {
  currentDate: '2017-10-20 12:30:00',
  endDate: '2017-10-20 13:00:00',
  tz: 'America/Chicago',
  iterator: false
};

try {
  var interval = parser.parseExpression('0 */2 * * * *', options);

  while (true) {
    try {
      var obj = interval.next();
      console.log(obj.getTime(), obj.toString());
    } catch (e) {
      break;
    }
  }
} catch (err) {
  log.error('Error: ' + err.message);
}

```
Let me know if this works for you. Cheers

**Comment by Eric24** [comment]
@santigimeno : Yep, that did the trick. Very subtle, but it makes sense. Thank you for your help!
