### ISSUE TITLE
Does not support '?'

### ISSUE THREAD

**Issue by ykhli** [harrisiirak/cron-parser#116]
In lots of cases(e.g Quartz, aws schedule expression) the support for cron expressions defaults to having either day of month or day of week to be '?' so that there's no ambiguity in meanings.

**Comment by rajeshwarpatlolla** [comment]
When i tried with `0 0 6 ? * 2,3,4,5,6,7,1 *` it's giving me error `Error: Invalid characters, got value: ?`

**Comment by Yonysun** [comment]
I met the same problem

**Comment by olivierto** [comment]
+1 you should definitly consider question mark

**Comment by chris-armstrong** [comment]
PR #128 is probably relevant here.

**Comment by harrisiirak** [comment]
Closed by #128
