### ISSUE TITLE
"*/45 * * * * *"

### ISSUE THREAD

**Issue by ashishpatel1992** [harrisiirak/cron-parser#118]
Why does */45 * * * * * shows two times at 00 and 45 of the second.
It is supposed to show up at 45 only
```
var interval = parser.parseExpression('*/45 * * * * *');
console.log(interval._fields.second);
```
Current Output:
`[ 0, 45 ]`
Expected Output:
`[ 45 ]`

**Comment by santigimeno** [comment]
My understanding is that this is not a bug but how cron works. See: https://stackoverflow.com/a/27412884/1562178 for an explanation. Anyway let's see what others think.

**Comment by ashishpatel1992** [comment]
Yes you are right. @santigimeno
