### ISSUE TITLE
Parser skips Sunday

### ISSUE THREAD

**Issue by VaidotasSm** [harrisiirak/cron-parser#119]
We have scheduled job running using `cron-parser` and noticed that task was run on Friday (OK), Monday(today - OK), but was not run on Sunday which supposed to happen. 

- The CRON expression was - `'30 16 * * 1,3,5,7'` which according to https://crontab.guru/#30_16_*_*_1,3,5,7 should have happened on Sunday.
- `cron-parser` version is `2.4.3`

Reproduced example using Sinon's `useFakeTimers`:
```JavaScript
const parser = require('cron-parser');
const TZ_ASIA_HONG_KONG = 'Asia/Hong_Kong';

it.only('cron-parser issue', () => {
  clock = sinon.useFakeTimers(moment.tz('2018-03-23 16:30', TZ_ASIA_HONG_KONG).toDate().getTime());

  const interval = parser.parseExpression('30 16 * * 1,3,5,7', {
    currentDate: moment().format(),
    tz: TZ_ASIA_HONG_KONG
  });

  // CronDate { _date: moment.parseZone("2018-03-23T16:30:00.000+08:00") }
  console.log(interval.prev());
  // CronDate { _date: moment.parseZone("2018-03-26T16:30:00.000+08:00") }
  console.log(interval.next());

  // Where is 2018-03-25T16:30 ???
});
```

**Comment by santigimeno** [comment]
Possible fix in: https://github.com/harrisiirak/cron-parser/pull/120

**Comment by harrisiirak** [comment]
@santigimeno @VaidotasSm merged PR with fix in.
