### ISSUE TITLE
Does not support '#'

### ISSUE THREAD

**Issue by yoavapi** [harrisiirak/cron-parser#124]
'#' is allowed for the day-of-week field, and must be followed by a number between one and five. It allows you to specify constructs such as "the second Friday" of a given month. For example, entering "5#3" in the day-of-week field corresponds to the third Friday of every month.

**Comment by harrisiirak** [comment]
Yet it doesn't seem to part of standard cron syntax. I'm wrong? It seems to be part of CronTrigger/Quartz. Still, the idea itself is worthy to be considered. Adding this as feature request.

**Comment by kramer65** [comment]
@harrisiirak - Thanks for pointing me here.

We would be extremely happy with this feature. Are there any plans to implement this anytime soon?

**Comment by kramer65** [comment]
@harrisiirak - Would you be willing to accept a donation to add support for `#` to this library? We could maybe spare say $250?

**Comment by harrisiirak** [comment]
@kramer65 I'll look into this and try to understand how much work implementing this feature is. I'll be back to you by end of this week.

**Comment by harrisiirak** [comment]
@kramer65 @yoavapi as I was suspecting this is little bit more difficult to implement. I did put something together, but this isn't good enough (doesn't handle some edge cases very well) to be pushed/merged into master branch. At this point I'll add this as priority for `3.0`. I'm not completely burying this for `2.x` branch as well, as I may have some enlightenment and find better solution.

No ETA for this at the moment, I'll try to start with as soon as possible.

**Comment by justintime4tea** [comment]
Also does not support ? as far as I know... could be wrong...

**Comment by mdbiundo** [comment]
Is there a way to achieve the "third Tuesday of every month" behavior with recurrence rules?  I don't need cron syntax, and the readme says 

> But if you want to, say, "run this function at the :20 and :50 of every hour on the third Tuesday of every month," you'll find that Node Schedule suits your needs better.

so maybe I'm missing something?  Watching this thread for any updates, thanks!

**Comment by kramer65** [comment]
@mdbiundo - I guess this lib is meant: https://github.com/node-schedule/node-schedule
I don't have experience with it though, s go check it out.

**Comment by mdbiundo** [comment]
@kramer65 Whoops you're right I mixed up my browser tabs, meant to be looking at that one.

**Comment by harrisiirak** [comment]
Closed by #155 
Credits are going to @DiskImage 
CC @kramer65 @yoavapi
