### ISSUE TITLE
This problem confuse me,  bug or  feature?

### ISSUE THREAD

**Issue by chaosJS** [harrisiirak/cron-parser#126]
![menu saveimg savepath20180702183959](https://user-images.githubusercontent.com/17522683/42159778-8b2e7d02-7e27-11e8-8c02-fcf8c7c04f28.jpg)

if i pass an empty string ,it'll parse to current date

**Comment by chaosJS** [comment]
@harrisiirak

**Comment by harrisiirak** [comment]
@chaosJS if the fields are not set, it will default to this pattern: https://github.com/harrisiirak/cron-parser/blob/master/lib/expression.js#L124

**Comment by chaosJS** [comment]
got it, thanks a lot .
Also , when i tried this: '0 0 12 * * ?'  i got an  error: 'Error: Invalid characters, got value: ?'
![image](https://user-images.githubusercontent.com/17522683/42226521-beabea62-7f11-11e8-848d-aadd052bcb58.png)
@harrisiirak

**Comment by harrisiirak** [comment]
@chaosJS see #116

**Comment by harrisiirak** [comment]
Closed by #128
