### ISSUE TITLE
Out of bounds day of month causes hasNext() = false when it is expected to produce true

### ISSUE THREAD

**Issue by braintapper** [harrisiirak/cron-parser#127]
`cron-parser` is generally good about skipping over invalid dates (Feb 31, Apr 31) when explicit days of the month and/or explicit months are provided in the cron expression.

In a situation where there are possible valid and invalid dates (i.e. a list of months that include 31 days and 30 days), I expect `.hasNext()` to always be true, because there will be at least one valid date from the expression.

See examples below:

```javascript
parser = require('cron-parser')
options = {
  currentDate: new Date() // Fri Jul 27 2018 15:45:08 GMT-0400 (Eastern Daylight Time)
}

interval = parser.parseExpression("0 0 0 31 1,2,3,4,5 *", options)
interval.hasNext() 
// true, because month 1 has 31 days. 
// iterating will continue to produce results, skipping over months 2 and 4
// "Thu Jan 31 2019 00:00:00 GMT-0500"
// "Sun Mar 31 2019 00:00:00 GMT-0400"
// "Fri May 31 2019 00:00:00 GMT-0400"
// "Fri Jan 31 2020 00:00:00 GMT-0500"
// "Tue Mar 31 2020 00:00:00 GMT-0400"

interval = parser.parseExpression("0 0 0 31 2,3,4,5 *", options)
interval.hasNext() 
// false, because month 2 has 28 days, won't skip over months 2 and 4, can't iterate

interval = parser.parseExpression("0 0 0 31 2,3,4,5,8 *", options)
interval.hasNext() 
// true, because month 8 has 31 days
// iterating will continue only once until it hits month 2
// "Fri Aug 31 2018 00:00:00 GMT-0400"
// Invalid explicit day of month definition

// change the currentDate to see if it has an impact

options.currentDate = new Date("03/01/2018")
interval = parser.parseExpression("0 0 0 31 2,3,4,5,8 *", options)
interval.hasNext() 
// false, even though month 3 has 31 days, 

interval = parser.parseExpression("0 0 0 31 1,2,3,4,5,8 *", options)
interval.hasNext() 
// true, but the start date hasn't changed. for the bug to be consistent, i expect .hasNext() to be false
// I only added a 1 to the front of the month list, but 1 has 31 days, which makes it a valid month/day combination
// iterating will continue to produce results, skipping over months 2 and 4
// "Sat Mar 31 2018 00:00:00 GMT-0400"
// "Thu May 31 2018 00:00:00 GMT-0400"
// "Fri Aug 31 2018 00:00:00 GMT-0400"
// "Thu Jan 31 2019 00:00:00 GMT-0500"
// "Sun Mar 31 2019 00:00:00 GMT-0400"
```
Because the month lists have multiple months that include at least one valid month containing 31 days, I expect interval.hasNext() to be true in *all* the cases above. When the first month to be iterated on fails date validation, the invalid date skipping is not invoked.

**Comment by santigimeno** [comment]
Yeah, these seems like bugs to me

**Comment by fishcharlie** [comment]
I'm working on testing all of these to see if I can help fix this. In the following example.

```
interval = parser.parseExpression("0 0 0 31 2,3,4,5,8 *", options)
interval.hasNext() 
// true, because month 8 has 31 days
// iterating will continue only once until it hits month 2
// "Fri Aug 31 2018 00:00:00 GMT-0400"
// Invalid explicit day of month definition
```

Commenting out the following lines seems to fix it.

https://github.com/harrisiirak/cron-parser/blob/2e3f6db007a8439d5458b8acb98027d08f635d38/lib/expression.js#L455-L457

But commenting out those lines causes other problems (tests not passing).

I'm gonna keep investigating, but just logging what I find here, in case it helps anyone else fix this.

**Comment by harrisiirak** [comment]
@santigimeno @braintapper if you can, please look into this: https://github.com/harrisiirak/cron-parser/pull/152. It possibly is fixing this issue. Let me know if I missed something here.
