### ISSUE TITLE
Error: Invalid characters, got value: 1#1

### ISSUE THREAD

**Issue by kramer65** [harrisiirak/cron-parser#129]
I'm using the following cron, which I expect to run every first monday of the month at 13.00 hours.

    0 13 * * MON#1

Unfortunately I get an error saying `Error: Invalid characters, got value: 1#1`. Since we use this a lot, it would be really awesome if this could be fixed.

I'm not sure but maybe this is related to #107 in which @santigimeno and @basvdijk discuss the usage of `SAT-SUN`. That one doesn't seem to have been resolved though.

[EDIT]
I tried simply adding `\d#\d` to the regex here: https://github.com/harrisiirak/cron-parser/blob/master/lib/expression.js#L155-L157 . But after that it hangs and I then kinda got lost in the code. Any idea where this is hanging or where it could be added?

**Comment by harrisiirak** [comment]
@kramer65 see #124

**Comment by harrisiirak** [comment]
@kramer65 closing this in favour of #124. This is still relevant!
