### ISSUE TITLE
Error next time

### ISSUE THREAD

**Issue by zhangxiang958** [harrisiirak/cron-parser#139]
i find '* 0 0 1,2 * * *' this expression when i want to get NextTime, it will return 2018-12-02 00:00:00, is that is bug? how to fix ?

**Comment by santigimeno** [comment]
@zhangxiang958 can you post a sample code that demonstrates the issue?

**Comment by zhangxiang958** [comment]
@santigimeno 
```
const cronParser = require('cron-parser');

let interval = cronParser.parseExpression('* 0 0 1,2 * * *');
let next = interval.next().toString();
console.log(next);
```
i expect next is 2018-12-05 00:00:00 but actually got 2018-12-06 00:00:00

**Comment by santigimeno** [comment]
I'm not sure I understand, but that expression is incorrect as it has 7 fields instead of 5 or 6. Anyway, what do you exactly want to accomplish with that cron expression?

**Comment by zhangxiang958** [comment]
@santigimeno same result with * 0 0 1,2 * *

**Comment by santigimeno** [comment]
I've modified your code to print the next 10 dates and it looks it's working correctly:

```
Sun Dec 02 2018 00:00:00 GMT+0100
Sun Dec 02 2018 00:00:01 GMT+0100
Sun Dec 02 2018 00:00:02 GMT+0100
Sun Dec 02 2018 00:00:03 GMT+0100
Sun Dec 02 2018 00:00:04 GMT+0100
Sun Dec 02 2018 00:00:05 GMT+0100
Sun Dec 02 2018 00:00:06 GMT+0100
Sun Dec 02 2018 00:00:07 GMT+0100
Sun Dec 02 2018 00:00:08 GMT+0100
Sun Dec 02 2018 00:00:09 GMT+0100
```

**Comment by zhangxiang958** [comment]
@santigimeno no, i expect:
```
Sun Dec 01 2018 00:00:00 GMT+0100
Sun Dec 01 2018 00:00:01 GMT+0100
Sun Dec 01 2018 00:00:02 GMT+0100
Sun Dec 01 2018 00:00:03 GMT+0100
Sun Dec 01 2018 00:00:04 GMT+0100
Sun Dec 01 2018 00:00:05 GMT+0100
Sun Dec 01 2018 00:00:06 GMT+0100
Sun Dec 01 2018 00:00:07 GMT+0100
Sun Dec 01 2018 00:00:08 GMT+0100
Sun Dec 01 2018 00:00:09 GMT+0100
```
because from today, Dec 01 is closer than Dec 02

**Comment by zhangxiang958** [comment]
@santigimeno sorry about that sample

```
const cronParser = require('cron-parser');

let interval = cronParser.parseExpression('* 0 0 1,2 * * *');
let next = interval.next().toString();
console.log(next);
```
i expect next is 2018-12-01 00:00:00 but actually got 2018-12-02 00:00:00

**Comment by santigimeno** [comment]
Yes, that's correct. There's indeed an error. Let me see

**Comment by zhangxiang958** [comment]
@santigimeno i found that code maybe where is the problem:
in expression.js at line 342:
```
if ((method === 'Month') || (method === 'Day')) {
        currentDate.addHour();
} else {
     // Ending DST
     if (this._fields.hour.length !== 24) {
     // Hour is specified
     this._dstEnd = currentHour;
}
```
i think maybe when method is Month or Day, it should not addHour, do you agree?

**Comment by santigimeno** [comment]
I think it should be fixed by: https://github.com/harrisiirak/cron-parser/pull/140

**Comment by zhangxiang958** [comment]
@santigimeno it seem to be fixed. can you publish this newer package ?
