### ISSUE TITLE
Wrong next times

### ISSUE THREAD

**Issue by ketysek** [harrisiirak/cron-parser#142]
Hi there,
I've found bug when the parsed cron contains repeat and the repeat minutes is greater than 60 or repeat hours is greater than 24, for example:
- */90 * * * * (repeat every 90 minutes) or 
- \* */36 * * * (repeat every 36 hours). 

In the first case, the next datetimes are every hour every day - 20:00, 21:00, 22:00 etc.
In the second case, the next datetimes are every day at 0:00 hour.

**Comment by harrisiirak** [comment]
@ketysek the patterns you are using aren't valid.
Valid value range for minutes is 0 - 59.
Valid value range for hours is 0 - 23.
See the documentation and/or RFC and wiki.

**Comment by ketysek** [comment]
Ah, Okay! thanks for explanation!

**Comment by ketysek** [comment]
Hm, I have to reopen it, because if I set repeat every 45 minutes, it's wrong ... see the formatted output datetimes:
01:00, 14.12.2018
01:45, 14.12.2018
02:00, 14.12.2018 <-- this should be 2:30

**Comment by ketysek** [comment]
Ok, I'm wrong again: 
Note that frequencies in general cannot be expressed; only step values which evenly divide their range express accurate frequencies (for minutes and seconds, that's /2, /3, /4, /5, /6, /10, /12, /15, /20 and /30 because 60 is evenly divisible by those numbers; for hours, that's /2, /3, /4, /6, /8 and /12);
