### ISSUE TITLE
Day of week goes from 0-7 instead of 0-6

### ISSUE THREAD

**Issue by pranavrc** [harrisiirak/cron-parser#143]
https://github.com/harrisiirak/cron-parser/blob/d197e25b4ec5dce4c65dbe18dc31b954f56dddce/lib/expression.js#L67 Right there

**Comment by harrisiirak** [comment]
@pranavrc sure, but I'm not completely sure if I understand what are you trying to refer to.

> 0-7 (0 or 7 is Sunday, or use names)

It's pretty standard to handle 0 and 7 both as "Sunday" here.

**Comment by pranavrc** [comment]
Yikes my bad, I thought this was a bug, but then I found this: https://unix.stackexchange.com/questions/106008/day-of-week-0-7-in-crontab-has-8-options-but-we-have-only-7-days-in-a-week

Closing.
