### ISSUE TITLE
Daily parser not working, when you have something like this : 1 6 8 1/20 * ? * 

### ISSUE THREAD

**Issue by alin0509** [harrisiirak/cron-parser#148]
when you want to parse an expression, every **x** days at some hour (for ex 00:00:00), you will have something like this: 0 0 0 1/**x** * ? * , the value for the next or previous date is the first date of the month which is wrong. I ques you don't parse the 1/x correctly.

 `var cronParser = require("cron-parser"); 
var interval = cronParser.parseExpression('0 0 8 1/3 * ? *'); 
console.log('Date: ', interval.prev().toString())
console.log('Date: ', interval.next().toString())`

Result:
"Date: ","Fri Feb 01 2019 08:00:00 GMT+0200"
"Date: ","Fri Mar 01 2019 08:00:00 GMT+0200"

Wich is wong

**Comment by natekspencer** [comment]
@alin0509, the cron expression you have listed is non-standard. The following should give you what you want and works with the current code:
`0 0 8 */3 * *`
