### ISSUE TITLE
no validation for '* * * * * * * *ASDS'

### ISSUE THREAD

**Issue by MykolaPanko** [harrisiirak/cron-parser#149]
I was trying to parse '* * * * * * * *ASDS' thru cron-parser and noticed that no any error for such case (not valid time) [https://www.screencast.com/t/OfU29nW6AH](url)

**Comment by harrisiirak** [comment]
@MykolaPanko the parser is looking up values separated by whitespace. Only first 5 + 1 (standard + optional second field) atom values are processed, everything else coming after that will be discarded.

However, throwing an error in such situation may be useful.
