### ISSUE TITLE
cron parser next date is wrong

### ISSUE THREAD

**Issue by kumar-muthu** [harrisiirak/cron-parser#154]
Here is the code to reproduce it

```
var parser = require('cron-parser');
var options = {
    currentDate: '2019-02-01'
};

var interval = parser.parseExpression('0 0 1 */2 *', options); // Every 2 months
  [1, 2, 3, 4, 5].forEach((i) => {
    console.log('Date: ', interval.next().toDate().toDateString());
});

// Prints

// Date:  Fri Mar 01 2019
// Date:  Wed May 01 2019
// Date:  Mon Jul 01 2019
// Date:  Sun Sep 01 2019
// Date:  Fri Nov 01 2019`
```

But actually the next date should start from April 01 2019. Is this a bug or I have misunderstood the implementation ?

**Comment by harrisiirak** [comment]
@kumar-muthu this is how steps are working with cron expressions. It will yield a predictable value/state that doesn't change or depend on the current system time. The expressions itself is absolute truth.

The simpliest example (minute step):

`*/5 * * * *` => `0, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55`

Your case (mont step):

`0 0 1 */2 *` => `1, 3, 5, 7, 9, 11`

Let's say that you change the date to `2019-06-01`. This doesn't yield as `2019-08-01` but `2019-07-01` as this expression was initially deconstructed.

**Comment by kumar-muthu** [comment]
@harrisiirak Thanks. Makes sense.
