### ISSUE TITLE
error "Invalid explicit day of month definition" with */5 in day and some explicit months

### ISSUE THREAD

**Issue by john30** [harrisiirak/cron-parser#158]
e.g. the following fails:
`* * * */5 6 *`

whereas this is fine:
`* * * */5 1 *`

tested on the day of submitting this issue

**Comment by harrisiirak** [comment]
@john30 pushed the fix (823502b) into the master branch. Let me know how this works for you. Will publish new npm release soon.

**Comment by john30** [comment]
looks good for me
