### ISSUE TITLE
To which Cron standard does this library try to adhere to?

### ISSUE THREAD

**Issue by jhorbulyk** [harrisiirak/cron-parser#159]
When I searching across the Internet for examples of Cron usage and Cron parsing tools, I see some tools with 5 input places and some with 6 (the sixth being for a seconds field). Furthermore, I see some flavors which support `?` character as a valid input while other variants do not.

To what standard or what set of variants does this library try to adhere to?

**Comment by harrisiirak** [comment]
@jhorbulyk it supports standard set (`*,-` etc) of the syntax + some non-standard characters (`#?/`). Definitely, the documentation could be improved to reflect supported functionality in a better way.
