### ISSUE TITLE
what is the different between startDate and currentDate

### ISSUE THREAD

**Issue by ijunbin** [harrisiirak/cron-parser#161]
i  have confused between the option param startDate and currentDate ,because i find the the describe 'currentDate - Start date of the iteration'  from README  
but what is the startDate option do?

**Comment by ahuggins-nhs** [comment]
The behavior is pretty easy to test. startDate behaves as a point in time at which the cron schedule begins, whereas currentDate sets the start of the iteration of possible points in time where the schedule occurs and is generally the current point in time if not set.

**Comment by bryceg** [comment]
From looking at the code, I believe it's for iterating in reverse from currentDate using prev() or similar when defining your range of acceptable dates.

https://github.com/harrisiirak/cron-parser/blob/6eae107aef5cb137858ae5a79e8385c36e257b6b/lib/expression.js#L463

**Comment by harrisiirak** [comment]
`startDate` and `endDate` are optional parameters that defines possible date range for iteration. When the iteration reaches beyond these constraints, it will throw an exception.
