### ISSUE TITLE
Cannot find module "./data/packed/latest.json"

### ISSUE THREAD

**Issue by xiannv** [harrisiirak/cron-parser#165]
#### There is a error
![image](https://user-images.githubusercontent.com/24910356/61636001-52416e80-acc7-11e9-8cba-ee5caa06ba7e.png)

**Comment by xiannv** [comment]
+ cron-parser@2.12.0

**Comment by harrisiirak** [comment]
@xiannv can you help me understand how this error is related to `cron-parser` package?
