### ISSUE TITLE
Typescript CronExpression.next wrong declaration for iterator

### ISSUE THREAD

**Issue by Zaitsev** [harrisiirak/cron-parser#168]
when using `parseExpression(cronString, {iterator: true, utc: true,});`  next() returns {done:bool,value:CronDate} but TS declaration is for _no-iterator_  mode only

**Comment by harrisiirak** [comment]
See comment here: https://github.com/harrisiirak/cron-parser/issues/175#issuecomment-631421735 and #82 
We need better ES6 support here.
