### ISSUE TITLE
Error Parsing expression '0/30 * * * * ?'

### ISSUE THREAD

**Issue by LoveofRedMoon** [harrisiirak/cron-parser#169]
Something may got different when parsing expression.

Expression '0/30 * * * * ?' means
run at   0 seconds per 30 seconds   on every minute

![image](https://user-images.githubusercontent.com/35391556/65019305-877fdb00-d95d-11e9-97ad-af81b59e2fa7.png)
When I see the code,  It may cause with this code.

'0/30' should parse to '0-59/30' not to '0'

so the code may modify to 

![image](https://user-images.githubusercontent.com/35391556/65020291-7e900900-d95f-11e9-9947-420a50252479.png)

(P.S. I only consider the standardValidCharacters, And haven't fully test)

**Comment by harrisiirak** [comment]
Resolved by https://github.com/harrisiirak/cron-parser/commit/bce1a6ec0df32975bad02a30c06cf816d1d46961
