### ISSUE TITLE
Export moment or moment API

### ISSUE THREAD

**Issue by ph-fuergy** [harrisiirak/cron-parser#171]
Do you think is possible to export moment or moment API ( e.g. moment.format ).
Now I need to do:

```
if (iterator.hasNext()) {
    iterator.next()._date.format('...'); // use private attribute
    ...
}
```

I think more elegant would be call:

```
iterator.next().format('...')
// or
iterator.next().moment.format('...')
// or something else
```

**Comment by Floriskoch** [comment]
@ph-fuergy I added a PR for this: https://github.com/harrisiirak/cron-parser/pull/201

**Comment by harrisiirak** [comment]
@ph-fuergy @Floriskoch as momentjs itself is now deprecated, we're planning to move away from it (see https://github.com/harrisiirak/cron-parser/issues/195). So yeah, that said, I would avoid adding anything momentjs specific to this library.

I understand that this elegant and convenient way to handle/manipulate data instances, but this isn't really something that belongs to the core functionality.
