### ISSUE TITLE
Cron parser should not support jobs scheduled in seconds

### ISSUE THREAD

**Issue by utsavk1993** [harrisiirak/cron-parser#172]
Ideally, Cron job cannot be used to schedule a job in a seconds interval. Can you provide an option to disable it and throw an error if some user schedules the job in seconds
E.g. `*/30 * * * *`

**Comment by harrisiirak** [comment]
@utsavk1993 it sounds like a reasonable addition.

**Comment by harrisiirak** [comment]
I'll close it in favour of https://github.com/harrisiirak/cron-parser/issues/249 (optionally disabling cron extensions)
