### ISSUE TITLE
Day of month and days of week

### ISSUE THREAD

**Issue by cartuchogl** [harrisiirak/cron-parser#173]
When combined in an expression both a day of the month and days of the week I believe that the behavior is incorrect.

I think the following test shows the problem.

````js
// day_of_week_and_day_of_month.js
var test = require('tap').test;
var CronExpression = require('../lib/expression');

test('It works with days of weeks and day of month', function(t) {
  try {
    var interval, date;

    interval = CronExpression.parse('0 4 1 * 1-5');

    for (var i = 0; i < 10; i++) {
      date = interval.next();
      t.equal(date.getDate(), 1, 'on the 1th');
    }
  } catch (err) {
    t.ifError(err, 'Interval parse error');
  }

  t.end();
});
````

I think all of the generated dates should be the first day of the month when match day of the week.

Previously I used [later](http://bunkat.github.io/later/) and if it shows this behavior.

Thanks.

**Comment by harrisiirak** [comment]
@cartuchogl thanks for the report! Currently, this behavior is/seems to be expected.

https://pubs.opengroup.org/onlinepubs/007904975/utilities/crontab.html

> If month, day of month, and day of week are all asterisks, every day shall be matched. If either the month or day of month is specified as an element or list, but the day of week is an asterisk, the month and day of month fields shall specify the days that match. If both month and day of month are specified as an asterisk, but day of week is an element or list, then only the specified days of the week match. **Finally, if either the month or day of month is specified as an element or list, and the day of week is also specified as an element or list, then any day matching either the month and day of month, or the day of week, shall be matched.**

Also: https://crontab.guru/#0_4_1_*_1-5 - produces the same result.

**Comment by cartuchogl** [comment]
Thanks for your reply.
