### ISSUE TITLE
Types are incorrect when using es6 iterator flag

### ISSUE THREAD

**Issue by wj-eurostar** [harrisiirak/cron-parser#175]
When using the flag `iterator: true` the value returned by the iterator does not match the typescript types.

For this code:
```
const interval = parser.parseExpression('*', {
    currentDate,
    endDate,
    iterator: true
});
cost obj = interval.next().value;
```

The following error is shown.
`Property 'value' does not exist on type 'CronDate'.`

The methods such as toString, toDate etc are only accessible through interval.next().value.toString, interval.next().toDate when using this flag.

**Comment by tobiasjeckel** [comment]
Anyone know  a fix or workaround? Thanks

**Comment by harrisiirak** [comment]
This library isn't currently supporting ES6 style iterators (neither the parser is compatible with it), therefore `next()` isn't returning correct iterator as you could expect.

The best you can do at this point: `cost obj = interval.next() as IteratorResult<CronDate>`

See #82
