### ISSUE TITLE
Week Variable New Year Wrong Parsing.

### ISSUE THREAD

**Issue by isikhi** [harrisiirak/cron-parser#176]
```
let spec = '0 0 11 23-28 12 3';
const cronDateFormat = cronParser.parseExpression(spec);
const cronDateToString = cronDateFormat.next()
  .toString();
spec = new Date(cronDateToString);
```
//Output is: 2019-12-24T11:00:00.000Z

But when I try to this option for 
let spec = '0 0 11 23-28 2 3';
Output will be: `2020-02-05T11:00:00.000Z`
The output should be "At 11:00 on every day-of-month from 23 through 28 and on Wednesday in February.”

**Comment by harrisiirak** [comment]
@isikhi please see this issue: https://github.com/harrisiirak/cron-parser/issues/173

Shortly:

> Finally, if either the month or day of month is specified as an element or list, and the day of week is also specified as an element or list, then any day matching either the month and day of month, or the day of week, shall be matched.

This by design and RFC and is not going to change.

https://crontab.guru/#0_11_23-28_2_3
http://cron.schlitt.info/index.php?cron=0+11+23-28+2+3&iterations=10&test=Test

**Comment by isikhi** [comment]
Actually i dont understand your examples. First one is okay for me but second one is not okay.
How can i know which one is selected? 
I want to write an expression that run on wednesday on 4th week of February. how can i write that?
