### ISSUE TITLE
Error: cron_parser__WEBPACK_IMPORTED_MODULE_25___default.a.parseExpression is not a function

### ISSUE THREAD

**Issue by thangdo0212** [harrisiirak/cron-parser#181]
error when i run  simple expression

var parser = require('cron-parser');
 
try {
  var interval = parser.parseExpression('*/2 * * * *');
 
  console.log('Date: ', interval.next().toString()); // Sat Dec 29 2012 00:42:00 GMT+0200 (EET)
  console.log('Date: ', interval.next().toString()); // Sat Dec 29 2012 00:44:00 GMT+0200 (EET)
 
  console.log('Date: ', interval.prev().toString()); // Sat Dec 29 2012 00:42:00 GMT+0200 (EET)
  console.log('Date: ', interval.prev().toString()); // Sat Dec 29 2012 00:40:00 GMT+0200 (EET)
} catch (err) {
  console.log('Error: ' + err.message);
}

**Comment by harrisiirak** [comment]
@thangdo0212 it's really hard to say anything without knowing what configuration is exactly used for Webpack. Can you provide a little bit more details? Thanks!

**Comment by thangdo0212** [comment]
> @thangdo0212 it's really hard to say anything without knowing what configuration is exactly used for Webpack. Can you provide a little bit more details? Thanks!

**Comment by thangdo0212** [comment]
> @thangdo0212 it's really hard to say anything without knowing what configuration is exactly used for Webpack. Can you provide a little bit more details? Thanks!

Thank you. I have solved my problem
