### ISSUE TITLE
[00 00 * * *] expression does not create event for 00:00 time for a start date

### ISSUE THREAD

**Issue by shrutivardhan** [harrisiirak/cron-parser#187]
I am trying to create an event with the following cron expression : ["00 00 * * sat"] with following options 
{"currentDate":"2020-06-06","endDate":"2020-06-06T23:59:59.000Z","iterator":true,"tz":"UTC"}.
Its not generating the event for 6th june. However if the expression is changed to ["00 01 * * sat"], the event is generated with the following date 2020-06-06T23:01:00.000Z.

**Comment by harrisiirak** [comment]
@shrutivardhan can you please provide an example that generates such output?

I'm executing this pattern with following result: `Sat Jun 06 2020 01:00:00 GMT+0300`

**Comment by shrutivardhan** [comment]
Sat Jun 06 2020 01:00:00 GMT+0300 is not the expected result .. 
 Sat Jun 06 2020 00:00:00 GMT+0300 should have been created. following is the fhir repeat request that translates to .. generate events from 6th june to 6th June to 14th june at 00:00:00 once every week on a saturday.
{
            "period": 1,
            "periodUnit": "wk",
            "frequency": 1,
            "timeOfDay": [
                "00:00"
            ],
            "boundsPeriod": {
                "end": "2020-06-14",
                "start": "2020-06-06"
            }
        }
The corresponding cron expression is ["00 00 * * sat"]. The first date generated should be Sat Jun 06 2020 00:00:00 followed by Sat Jun 13 2020 00:00:00. the library is able to generate the 13th june event but not the 6th june one. It might be because of the time component because the current date printed is (Sat Jun 06 2020 00:00:00)

**Comment by harrisiirak** [comment]
Oh, I see. If you want to specify the iteration range, `startDate` must be provided (not `currentDate`).

```
const iter = parser.parseExpression('0 0 * * sat', {
  startDate: '2020-06-06',
  tz: 'UTC'
});

console.log(iter.next());
console.log(iter.next());
console.log(iter.next());
console.log(iter.next());
```

Yields:

```
CronDate { _date: Moment<2020-06-13T00:00:00Z> }
CronDate { _date: Moment<2020-06-20T00:00:00Z> }
CronDate { _date: Moment<2020-06-27T00:00:00Z> }
CronDate { _date: Moment<2020-07-04T00:00:00Z> }
```

**Comment by harrisiirak** [comment]
@shrutivardhan did use of `startDate` solved your issue?

**Comment by shrutivardhan** [comment]
@harrisiirak  Thanks! It worked using startDate.
