### ISSUE TITLE
Supplying 1 Hour Range Results in Parse Error

### ISSUE THREAD

**Issue by div-nick** [harrisiirak/cron-parser#188]
I am receiving a parse error when I try to supply a cron expression with a 1 hour time range.

This is the expression that I want parsed.
*/10 2-2 * * *

From my research on cron expressions, this should run every 10 minutes between 2:00am and 2:59am. As far as I can tell other ranges are parsed correctly.

**Comment by harrisiirak** [comment]
Hi!

> From my research on cron expressions, this should run every 10 minutes between 2:00am and 2:59am. As far as I can tell other ranges are parsed correctly.

Technically it isn't actually correct range definition but I see that some implementations handle it as it is `*/10 2 * * *` (2-2 yields 2).

However, this can be handled fairly easily. I'll add this to the backlog.
