### ISSUE TITLE
Cron expression with multiple ranges skips results

### ISSUE THREAD

**Issue by oliverjantar** [harrisiirak/cron-parser#191]
Hi, some cron expressions with multiple ranges in hours will skip results.
Example: cron '0 1-3,8-12,15-18 * * *'

will result in:
01:00
02:00
03:00
15:00
16:00
17:00
18:00

skips: 
08:00
09:00
10:00
11:00
12:00

It works fine with two ranges, but when there are more it starts to skip results.

**Comment by harrisiirak** [comment]
@oliverjantar thanks for reporting this. Look like this commit introduced this issue: https://github.com/harrisiirak/cron-parser/commit/110a82352c4c4d598cd2dddcd0d42fbf2def573e

**Comment by oliverjantar** [comment]
Thanks for fixing this!
