### ISSUE TITLE
Typescript error with version

### ISSUE THREAD

**Issue by huineng** [harrisiirak/cron-parser#192]
I have a typescript issue in your latest version "2.16.2"   typescript: 3.9.7

```
An export assignment cannot be used in a module with other exported elements
```

![image](https://user-images.githubusercontent.com/3482445/89712575-c3e66c00-d95f-11ea-96c1-6736a3a42601.png)

thanks

**Comment by gotoashishgupta** [comment]
I concur. Got error
`node_modules/cron-parser/lib/index.d.ts(1,1): error TS2309: An export assignment cannot be used in a module with other exported elements.` version 2.16+

**Comment by maplesteve** [comment]
Comes from this [commit](https://github.com/harrisiirak/cron-parser/commit/f5325886b74f9951a419a95dd1f368c2594e9217) which got merged though the check failed.
Update-PRs of some important repos of us are failing since then with the above error.

**Comment by harrisiirak** [comment]
Reverted this change in `2.16.3`. Let me know how this works for you.

> Comes from this commit which got merged though the check failed.

It was actually unrelated failure that was also fixed recently.

**Comment by maplesteve** [comment]
> Reverted this change in 2.16.3. Let me know how this works for you.

Our update PRs are happy again. Thanks!!

**Comment by huineng** [comment]
Perfect !
