### ISSUE TITLE
Value separator bug?

### ISSUE THREAD

**Issue by ySydorenko97** [harrisiirak/cron-parser#193]
I'm trying to check if the current time is valid for a cron expression. So i invoke `.prev()` first and then invoke `.next()`.
Here's an example:
currentDate: 'Fri, 14 Aug 2020 21:00:00 GMT'
cron: ''0 * * * 3,5''
`.prev()` result: 'Fri Aug 14 2020 20:00:00 GMT+0000'
`.next()` after invoke `.prev()`:  'Fri Aug 14 2020 21:00:00 GMT+0000'
Result: OK

But for cron with list of hours:
currentDate: 'Fri, 14 Aug 2020 21:00:00 GMT'
cron: '0 7,21 * * 3,5'
`.prev()` result: 'Fri Aug 14 2020 07:00:00 GMT+0000'
`.next()` after invoke `.prev()`:  'Wed Aug 19 2020 07:00:00 GMT+0000'
Result: Incorrect

Or even when I move 1 second forward for the same cron expression:
currentDate: 'Fri, 14 Aug 2020 21:00:01 GMT'
cron: '0 7,21 * * 3,5'
`.prev()` result: 'Fri Aug 14 2020 21:00:00 GMT+0000'
`.next()` after invoke `.prev()`:  'Wed Aug 19 2020 21:00:00 GMT+0000'
Result: Incorrect

P.S. for opposite invocation it works correctly.

**Comment by harrisiirak** [comment]
@ySydorenko97 thanks for reporting this, this is a bug!

```js
const parser = require('./');
const iter = parser.parseExpression('0 7,21 * * 3,5', {
  currentDate: 'Fri, 14 Aug 2020 21:00:00 GMT'
});

console.log(iter.prev());
console.log(iter.prev());
console.log(iter.next());
```

Double `prev()` call seems to do the thing, but yeah, this isn't a expected behaviour, I'll look into this.

**Comment by harrisiirak** [comment]
@ySydorenko97 actually, if I use my local timezone:

```js
const parser = require('./');
const iter = parser.parseExpression('0 7,21 * * 3,5', {
  currentDate: 'Fri, 14 Aug 2020 20:00:00',
});

console.log(iter.prev()); // 2020-08-14T07:00:00+03:00
console.log(iter.next()); // 2020-08-14T21:00:00+03:00
```

And actually, if you want to use UTC, you need to provide relevant timezone:

```
const parser = require('./');
const iter = parser.parseExpression('0 7,21 * * 3,5', {
  currentDate: 'Fri, 14 Aug 2020 20:00:00 GMT',
  tz: 'UTC'
});

console.log(iter.prev()); // 2020-08-14T07:00:00Z
console.log(iter.next()); // 2020-08-14T21:00:00Z
```

**Comment by harrisiirak** [comment]
@ySydorenko97 does this needs any further investigation or explanation?

**Comment by ySydorenko97** [comment]
@harrisiirak No, it's clear. Thank you for the answer.
