### ISSUE TITLE
Support for reversed ranges

### ISSUE THREAD

**Issue by Cynicszm** [harrisiirak/cron-parser#198]
Any chance cron-parser will be able to support reversed ranges, like 23-01 in hours? Currently throws an invalid range in expression.js but should mean (23,00,01).

      if (safeIsNaN(min) || safeIsNaN(max) ||
          min < constraints[0] || max > constraints[1]) {
        throw new Error(
          'Constraint error, got range ' +
          min + '-' + max +
          ' expected range ' +
          constraints[0] + '-' + constraints[1]
        );
      } else if (min >= max) {
        throw new Error('Invalid range: ' + val);
      }

**Comment by harrisiirak** [comment]
@Cynicszm probably not as it isn't something that standard (or some subsets of its) cron behaviour support, therefore getting an error here is an expected behaviour.
