### ISSUE TITLE
Specific date or last day of the month

### ISSUE THREAD

**Issue by shubhamms** [harrisiirak/cron-parser#199]
Given that the library now supports Last Day of the Month, what are your thoughts on adding support for if the date of the month does not exist then move to last day of the month. eg cron '10 20 30/L * *' where it would run on 30th for each month except feb where it would run on the 28th or the 29th (leap year). @harrisiirak

**Comment by harrisiirak** [comment]
@shubhamms can you eloborate on this a bit more?

Isn't the behaviour you're describing already working? When I use pattern `10 20 31,L * *`:

- When 31st day of the month exists, it returns this day
- When 31st day of month doesn't exists, the last day of the month is being used

Example:

 ` ` `
Sun Jan 31 2021 20:10:00
Sun Feb 28 2021 20:10:00
Wed Mar 31 2021 20:10:00 
Fri Apr 30 2021 20:10:00
 ` ` `

![image](https://user-images.githubusercontent.com/185315/103443464-30903900-4c68-11eb-9f6a-b57d2073a1c0.png)

Let me know if I missed something.

**Comment by shubhamms** [comment]
Hi @harrisiirak it works for 31,L but for 30,L it would be something like 30th and last day of the month. I was hoping we could do something like if the day of the month doesnt exist then run it on the last day of the month otherwise run it on the specified day. I looked at the code and I dont think it is doable because the check is done for each day. It would be possible if the next run date is calculated instead of each day being checked. If you think otherwise I would be happy to contribute

**Comment by harrisiirak** [comment]
@shubhamms oh, now I see what are thinking about, basically: "try to match 30th day of the month and if there is less days in the month, fallback to the last day of the month". The main issue here is that the standard cron pattern handling/matching doesn't support such behaviour (correct me, if I'm wrong), mixing such logic with sequences or intervals is rather confusing, therefore it also may need completely different syntax and behaviour matching for it (something like `10 20 30?L * *).

**Comment by shubhamms** [comment]
Yeah you are right I also came to the same conclusion. It is not a standard cron behavior and to implement what I want we would have to do something different than what this lib does. If you come across something that works like how I explained let me know. Otherwise I am ok for now. Thanks for checking :)

**Comment by mohsinamjad** [comment]
Hey @shubhamms were you able to solve this problem, I wanted to implement the exact same use-case e.g if cron is registered to 31 and month doesn't have 31 it should fallback to last day something like that.
