### ISSUE TITLE
Day of the month not honored when day of the week included

### ISSUE THREAD

**Issue by NodePing** [harrisiirak/cron-parser#205]
The day of the month doesn't appear to be calculated in with the next iteration if you also include the day of the week.

This cron expression, 0 5 2-8 * 4, should be "5 am on the 2nd through the 8th of the month if it's a Thursday" - so basically the second Thursday of each month.  When 'Thursday' is included, it completely ignores the 2-8 days of the month.

> new Date().toString();
'Sat Jan 09 2021 17:48:39 GMT+0000 (Coordinated Universal Time)'
> var parser = require('cron-parser');
> var interval = parser.parseExpression('0 5 2-8 * 4');
> console.log('Date: ', interval.next().toString());
Date:  Thu Jan 14 2021 05:00:00 GMT+0000

The 14th is outside the 2-8 day of the month range.

If you remove the day of the week from the cron expression, it honors the day of the month.

> var interval = parser.parseExpression('0 5 2-8 * *');
> console.log('Date: ', interval.next().toString());
Date:  Tue Feb 02 2021 05:00:00 GMT+0000

Likewise, if you remove the day of the month and leave in the day of the week, it iterates properly.

**Comment by harrisiirak** [comment]
@NodePing please see #173

Shortly:

> Finally, if either the month or day of month is specified as an element or list, and the day of week is also specified as an element or list, then any day matching either the month and day of month, or the day of week, shall be matched.

**Comment by NodePing** [comment]
My apologies.  I should have researched it more thoroughly.  Please delete or close this issue.
