### ISSUE TITLE
toISOString() behaviour changed in v3

### ISSUE THREAD

**Issue by lerouxb** [harrisiirak/cron-parser#206]
```javascript
const newSchedule = '*/10 * * * *';
const tz =  'America/New_York';

const interval = CronParser.parseExpression(newSchedule, { tz });

const prev = interval.prev();
console.error({ prev, 'prev.toISOString()': prev.toISOString() });
```

V2 output:

```javascript
{
  prev: CronDate { _date: Moment<2021-01-11T06:00:00-05:00> },
  'prev.toISOString()': '2021-01-11T11:00:00.000Z'
}
```

V3 output:

```javascript
{
  prev: CronDate {
    _date: DateTime {
      ts: 1610362800000,
      _zone: [IANAZone],
      loc: [Locale],
      invalid: null,
      weekData: [Object],
      c: [Object],
      o: -300,
      isLuxonDateTime: true
    }
  },
  'prev.toISOString()': '2021-01-11T06:00:00.000-05:00'
}
```

I can hack it to get the previous behaviour by doing `prev._date._getUTC().toISOString()`, but that's a bit of a hack. Less of a hack but a bit of a pain could be something like `(new Date(prev.getTime())).toISOString();`

One can argue whether the previous behaviour was right or wrong (I can argue both sides) as it is arguably odd passing in a time with timezone and ultimately getting out a date in UTC format, but I'd still like to get to the date and turn it into UTC somehow anyway.

Ways out would be to have an official way to get a luxon date out (no underscore methods) or to add a utc() or getUTC() method (unsure which name would be best), etc. Or maybe that method should return a CronDate to keep luxon hidden?

I'm wondering if this change should be documented as well.

**Comment by harrisiirak** [comment]
@lerouxb thanks for reporting this.

The idea behind `CronDate` is that its behaviour should be close to native `Date` implementation, therefore:

> The toISOString() method returns a string in simplified extended ISO format (ISO 8601), which is always 24 or 27 characters long (YYYY-MM-DDTHH:mm:ss.sssZ or ±YYYYYY-MM-DDTHH:mm:ss.sssZ, respectively). The timezone is always zero UTC offset, as denoted by the suffix "Z".

See more: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toISOString

I would say that we would like to retain native `Date` (and the way how previous version with `moment` implemented this) behaviour here. 

What I'm seeing as a solution/fix:

```
CronDate.prototype.toISOString = function() {
  return this._date.toUTC().toISO();
};
```

cc @andytson - what do you think about this?

**Comment by dmitry-yudakov** [comment]
Note that `toString()` output is changed as well.

v2:
```
Mon Jan 11 2021 08:32:00 GMT+0200
```

v3:
```
2021-01-11T08:32:00.000+02:00
```

**Comment by harrisiirak** [comment]
@dmitry-yudakov thanks, also a good point.

This can be possibly solved by passing the exactly the same format (defined ECMA-262 - https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toString#description) to `toFormat` function and return its results instead:

```js
CronDate.prototype.toString = function() {
  return this._date.toLocal().toFormat('EEE MMM d yyyy HH:mm:ss \'GMT\'ZZ \'(\'ZZZZZ\')\'');
};
```

Or well, even a simpler solution:

```js
CronDate.prototype.toString = function() {
  return this.toDate().toString();
};
```

**Comment by lerouxb** [comment]
Looks good. Any change we can get that as a 3.0.1 patch release? :)

**Comment by harrisiirak** [comment]
@lerouxb fixed this in https://github.com/harrisiirak/cron-parser/releases/tag/3.1.0
