### ISSUE TITLE
BUG: global is not defined since angular v6

### ISSUE THREAD

**Issue by mischahaenen** [harrisiirak/cron-parser#208]
Hello @Contributors
I am currently using your great project to convert cron expressions. When I've installed it, I had the error that global was not defined. I had a small workaround for this bug. I defined global myself in **polyfills.ts.** with **(window as any).global = window;**. Since angular v6, global is not defined by default. I was looking for another solution but found none, but I came across this comment:
https://github.com/angular/angular-cli/issues/9827#issuecomment-369578814
So is there a way that you can provide the global context? I think I'm not the only angular developer which faces this problem. And a solution from your side would save much time and saves some frustrated developers.
Thanks for your great work! 🚀

**Comment by harrisiirak** [comment]
@mischahaenen hi!

I'm not very familiar with Angular application build process anymore, at least it seems to be build process related issue. `cron-parser` itself doesn't use any global/window context as such, therefore I'm not completely sure what can be fixed from this side.

**Comment by amiram** [comment]
@harrisiirak I think this is by mistake. cron-parser is using this tree:
is-nan -> call-bind -> get-intrinsic -> has-symbols

has-symbols is using global in index.js:
```
var origSymbol = global.Symbol;
```

However, I didn't see any usage of is-nan in cron-parser code. Canthis dependency be removed?

**Comment by amiram** [comment]
@harrisiirak My mistake. It is used, but is it replaceable by something else? or do you know a way to override that in browser?

**Comment by harrisiirak** [comment]
@amiram `is-nan` is used but I think we can remove this dependency and rely on built-in `Number.isNaN `.
