### ISSUE TITLE
Invalid range: 23-23

### ISSUE THREAD

**Issue by jayaprakash** [harrisiirak/cron-parser#209]
I wanted to execute at 23 hours every day.

Here is the cron exp:  0 0 23/24 * * *
cron options: {"currentDate":"2021-01-21T21:34:17.000+0000","utc":true}

parseExpression resulted in Invalid range. Any inputs?

**Comment by harrisiirak** [comment]
@jayaprakash 

> I wanted to execute at 23 hours every day.

For this you don't need any ranges or steps, right? 
This should be achieved by this pretty basic pattern, by defining the hour value directly: `0 0 23 * * *`

There is also an open [ticket](https://github.com/harrisiirak/cron-parser/issues/156#issuecomment-506942668) for underlaying error. Steps without a valid range isn't allowed at this point.

**Comment by jayaprakash** [comment]
Thanks for the pointes. :)
