### ISSUE TITLE
Add support for specifying offset in the `*/n+x` format

### ISSUE THREAD

**Issue by NoNameProvided** [harrisiirak/cron-parser#215]
I would like to use the `*/n+x` format to specify an offset to my pattern. So the following example:
```
*/5+1 * * * *
```
logically equals to
```
01,06,11,16,21,26,31,36,41,46,51,56 * * * *
```

As workaround I can currently specify the desired behavior as

```
1-59/5 * * * *
```

#### Current behavior: 
A parsing error is thrown as this functionality is not supported currently.

```
Error: Invalid characters, got value: */5+1
```

#### Desired behavior

This pattern is supported.

**Comment by harrisiirak** [comment]
@NoNameProvided

Hi!

Can you also please provide me some examples where such syntax is supported? This doesn't seem to be something that is defined in standard (or any extended) RFC.

**Comment by NoNameProvided** [comment]
Hi! 

Thanks for the reply! This is not part of any standard as far as I know, I have found some examples of this pattern while googling around. I found it intuitive and would like to use it, thus I opened this feature request. However, I can understand if only standardized features are supported in `cron-parser`. In that case, this issue can be closed.

**Comment by DevXiaolan** [comment]
> Hi!
> 
> Thanks for the reply! This is not part of any standard as far as I know, I have found some examples of this pattern while googling around. I found it intuitive and would like to use it, thus I opened this feature request. However, I can understand if only standardized features are supported in `cron-parser`. In that case, this issue can be closed.

maybe we can implements this in some "plugin-way"

**Comment by harrisiirak** [comment]
> However, I can understand if only standardized features are supported in cron-parser. In that case, this issue can be closed.

Yes, I would like to keep it as close to UNIX cron format as possible (however, currently it also contains some non-standard features). As there is pretty sane workaround represented in standard format, I'm closing this one.
