### ISSUE TITLE
bug? . parseExpression  "* * 10 8-14,22-28 * 0"

### ISSUE THREAD

**Issue by sliently** [harrisiirak/cron-parser#216]
```js
var parser = require('cron-parser');

var options = {
  currentDate: new Date(),
};

try {
  var interval = parser.parseExpression('* * 10 8-14,22-28 * 0', options);
  console.log(interval)
  console.log('Date: ', interval.next().toString()); // Date:  Sun Mar 27 2016 01:00:00 GMT+0200
  console.log('Date: ', interval.next().toString()); // Date:  Sun Mar 27 2016 02:00:00 GMT+0200
  console.log('Date: ', interval.next().toString()); // Date:  Sun Mar 27 2016 04:00:00 GMT+0300 (Notice DST transition)
} catch (err) {
  console.log('Error: ' + err.message);
}
```

No 21 is set, but the next time 21 appears
![image](https://user-images.githubusercontent.com/29797646/111095527-95291780-8578-11eb-9ea1-04ef981e9f1b.png)

**Comment by harrisiirak** [comment]
@sliently  please see #173

Shortly:

> Finally, if either the month or day of month is specified as an element or list, and the day of week is also specified as an element or list, then any day matching either the month and day of month, or the day of week, shall be matched.

Which in your case translates to:

> At every minute past hour 10 on every day-of-month from 8 through 14 and every day-of-month from 22 through 28 and on Sunday.
