### ISSUE TITLE
"Invalid expression, loop limit exceeded" when using timezone in options

### ISSUE THREAD

**Issue by egeersoz** [harrisiirak/cron-parser#218]
Running into this in version 3.3.0:

```
var options = {
      currentDate: new Date(),
      tz: 'America/Chicago'
}
```

Code:
```
var cronParser = require('cron-parser')

let interval = cronParser.parseExpression("0 8 1,2 * *", options)
let next = interval.next()
```
Results in:
```
vue.runtime.esm.js?2b0e:1888 Error: Invalid expression, loop limit exceeded
    at CronExpression._findSchedule (expression.js?7a30:641)
    at CronExpression.next (expression.js?7a30:657)
```

It works if I remove the `tz` prop from the `options` object, but I need to specify the timezone. I also tried a string format for the date, but got the same error.

**Comment by harrisiirak** [comment]
@egeersoz that is very strange, the same code works locally for me. What is your TZ environment where are running this code?

**Comment by egeersoz** [comment]
I'm in America/Chicago.

**Comment by egeersoz** [comment]
The CronExpression seems to get generated fine:

![image](https://user-images.githubusercontent.com/1009235/112642403-464d6e80-8e11-11eb-9c63-f600687933e9.png)

Calling `next()` on that results in the error though.

**Comment by egeersoz** [comment]
I tried a few other timezones and they give the same error.

**Comment by egeersoz** [comment]
I spent the entire afternoon troubleshooting this. According to the debugger, the following if block is always executed until the 10,000th iteration is reached and the error is thrown:

![image](https://user-images.githubusercontent.com/1009235/112701424-9bfc3800-8e5e-11eb-9c70-f1330ffa3978.png)

After finding this out, I tested it by removing the "day of month" from the cron and replacing it with a wildcard:

```
0 8 * * *
```

This worked and no errors were thrown. However, any time I replace the day of month wildcard with comma-separated numbers, I get this error — but only when using the timezone option.

**Comment by bazineta** [comment]
Triggering the loop limiter tends to be caused by passing an invalid `currentDate`. Given that your test case passes here for me as well, and since it's triggered on seemingly any time zone, is it possible that for whatever reason the Date object you're passing there is for some reason invalid, e.g., the usual `Date` is getting overridden by an import of the same name that doesn't like a no-arg constructor, that sort of oddity.

**Comment by harrisiirak** [comment]
@egeersoz I have tried to reproduced this locally (overriding my own local TZ) but without any luck. Can you provide any standalone (environment/application agnostic) test case that yields that error?

RunKit example: https://runkit.com/embed/nxy0igf6q11e

> is it possible that for whatever reason the Date object you're passing there is for some reason invalid, e.g., the usual Date is getting overridden by an import of the same name that doesn't like a no-arg constructor, that sort of oddity.

Yeah, that's is also something that I'm suspecting.

> https://github.com/harrisiirak/cron-parser/issues/218#issuecomment-808240857

`options` seems to be a Observer?

**Comment by egeersoz** [comment]
@bazineta I get the error if I plug in a String date as `currentDate`, as well. For example, `2021-03-27 00:00:01` has the same issue. So I don't think it's a problem with the Date object.

I tested Firefox and it works fine there... Chrome and Edge seem to have this problem. I don't have the ability to test on Safari.

Logging the CronExpression in the console shows this in Firefox:

![image](https://user-images.githubusercontent.com/1009235/112764374-d33d2700-8fcd-11eb-9c6e-825ee1453a77.png)

Seems identical to Chrome:

![image](https://user-images.githubusercontent.com/1009235/112764350-aee14a80-8fcd-11eb-87f0-0b21edd0d9ec.png)

> `options` seems to be an Observer?

@harrisiirak I was just trying different methods. It's no longer an Observer — I'm just feeding it from a local variable now, with the same result:

```
      let opts = {
        currentDate: new Date(),
        tz: 'America/Chicago'
      }
      let interval = cronParser.parseExpression('0 8 1,2 * *', opts)
      console.log(interval)
      let next = interval.next()
```

![image](https://user-images.githubusercontent.com/1009235/112764650-2ebbe480-8fcf-11eb-8a4c-09bbf25a3751.png)

**Comment by harrisiirak** [comment]
I built browser bundle by using `browserify` and it seems to be working as expected.

<img width="826" alt="Screenshot 2021-03-30 at 12 18 56" src="https://user-images.githubusercontent.com/185315/113029660-59579a00-9195-11eb-8071-9f9ab2999126.png">

Bundle was created with command: `browserify index.js -o bundle.js`

Usage:

<img width="718" alt="Screenshot 2021-03-30 at 12 18 40" src="https://user-images.githubusercontent.com/185315/113029664-5a88c700-9195-11eb-83b7-9e17125ac141.png">

Results:

<img width="978" alt="Screenshot 2021-03-30 at 12 18 33" src="https://user-images.githubusercontent.com/185315/113029669-5c528a80-9195-11eb-990d-31d0d2002b78.png">

**Comment by harrisiirak** [comment]
@egeersoz were you able to solve this, or is there any way I can further help to debug the issue, that you were experiencing?

**Comment by egeersoz** [comment]
@harrisiirak Appreciate the follow-up! After spending two full days on this issue, I decided to go with a server-side solution to fetch the next occurrence date asynchronously once the page loads. I'll close this issue — thank you for your help.
