### ISSUE TITLE
Coverage improvement questions

### ISSUE THREAD

**Issue by bazineta** [harrisiirak/cron-parser#219]
I'm seeing if I can do something to improve coverage, and I think I've got a very complete set of tests now with respect to coverage on `expression.js`, with just two things I can't get coverage one. One of them I'm confused by, and the other I'm confounded by. Hoping that someone else will have some insight on these.

The first one, where I'm just confused, is here:
https://github.com/harrisiirak/cron-parser/blob/f36281a84612b84395b1b275c7e74a2e5e9b83f1/lib/expression.js#L573
The complete context is this:
```
    // Add or subtract day if select day not match with month (according to calendar)
    if (!dayOfMonthMatch && !dayOfWeekMatch) {
      this._applyTimezoneShift(currentDate, dateMathVerb, 'Day');
      continue;
    }

    // Add or subtract day if not day of month is set (and no match) and day of week is wildcard
    if (!isDayOfMonthWildcardMatch && isDayOfWeekWildcardMatch && !dayOfMonthMatch) {
      this._applyTimezoneShift(currentDate, dateMathVerb, 'Day');
      continue;
    }

    // Add or subtract day if not day of week is set (and no match) and day of month is wildcard
    if (isDayOfMonthWildcardMatch && !isDayOfWeekWildcardMatch && !dayOfWeekMatch) {
      this._applyTimezoneShift(currentDate, dateMathVerb, 'Day');
      continue;
    }

    // Add or subtract day if day of month and week are non-wildcard values and both doesn't match
    if (!(isDayOfMonthWildcardMatch && isDayOfWeekWildcardMatch) &&
        !dayOfMonthMatch && !dayOfWeekMatch) {
      this._applyTimezoneShift(currentDate, dateMathVerb, 'Day');
      continue;
    }
```
Where I'm confused here is that that first `if` statement is testing for `dayOfMonthMatch` and `dayOfWeekMatch` to both be  `false`; if they're both false, it restarts the loop, so none of the other `if` statements here will be executed. That last `if` statement is doing the same test, but the code is unreachable due to the first `if`. I think this last `if` can just go away entirely.

The second one, that I'm confounded by, is here:
https://github.com/harrisiirak/cron-parser/blob/f36281a84612b84395b1b275c7e74a2e5e9b83f1/lib/expression.js#L411
I can't seem to find any way to make that happen. If I understand the logic here, we just moved `currentDate` by an entire day or month step, then we're checking to see if the time didn't change. I can see that being an issue when moving by as little as an hour, when DST changeover is involved, but it seems that if we're moving by no less than a day, `currentDate` is certainly going to be different. Is there some circumstance where it wouldn't be different?

**Comment by harrisiirak** [comment]
Thanks for putting this together!

> Where I'm confused here is that that first if statement is testing for dayOfMonthMatch and dayOfWeekMatch to both be false; if they're both false, it restarts the loop, so none of the other if statements here will be executed. That last if statement is doing the same test, but the code is unreachable due to the first if. I think this last if can just go away entirely.

Yeah, I would say that one of them is duplicate and can be removed. 

> The second one

I'll investigate this a bit more, no clear idea about this atm. I can see that it was introduced in but #140 but in reality this code path is being never executed.

**Comment by harrisiirak** [comment]
@bazineta do you have any questions about this or can close it down?

**Comment by bazineta** [comment]
At this point, I'm confident the first one is dead code, and I haven't been able to find any path to the second one no matter what test or time zone I threw at it, so yeah, pretty sure that's dead too and this can be closed down.
