### ISSUE TITLE
Error while parsing L-1 or L-2

### ISSUE THREAD

**Issue by araskrj1992** [harrisiirak/cron-parser#227]
Problem : Trying to parse the expression created for AWS

Expression: 0 30 9 L-2 * *

Error: `Uncaught (in promise) Error: Constraint error, got range NaN-2 expected range 1-31
    at parseRange (expression.js:314)
    at parseRepeat (expression.js:279)
    at parseSequence (expression.js:254)
    at Function._parseField (expression.js:346)
    at parse (expression.js:834)
    at Function.parse (expression.js:887)
    at Function.parseExpression (parser.js:41)
    at _callee$ (JobSchedule.jsx:42)
    at tryCatch (runtime.js:63)
    at Generator.invoke [as _invoke] (runtime.js:293)
parseRange @ expression.js:314
parseRepeat @ expression.js:279
parseSequence @ expression.js:254
_parseField @ expression.js:346
parse @ expression.js:834
parse @ expression.js:887
parseExpression @ parser.js:41
_callee$ @ JobSchedule.jsx:42
tryCatch @ runtime.js:63
invoke @ runtime.js:293
(anonymous) @ runtime.js:118
asyncGeneratorStep @ asyncToGenerator.js:3
_next @ asyncToGenerator.js:25
Promise.then (async)
asyncGeneratorStep @ asyncToGenerator.js:13
_next @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
handleSubmit @ JobSchedule.jsx:32
onClick @ JobSchedule.jsx:171
callCallback @ react-dom.development.js:3945
invokeGuardedCallbackDev @ react-dom.development.js:3994
invokeGuardedCallback @ react-dom.development.js:4056
invokeGuardedCallbackAndCatchFirstError @ react-dom.development.js:4070
executeDispatch @ react-dom.development.js:8243
processDispatchQueueItemsInOrder @ react-dom.development.js:8275
processDispatchQueue @ react-dom.development.js:8288
dispatchEventsForPlugins @ react-dom.development.js:8299
(anonymous) @ react-dom.development.js:8508
batchedEventUpdates$1 @ react-dom.development.js:22396
batchedEventUpdates @ react-dom.development.js:3745
dispatchEventForPluginEventSystem @ react-dom.development.js:8507
attemptToDispatchEvent @ react-dom.development.js:6005
dispatchEvent @ react-dom.development.js:5924
unstable_runWithPriority @ scheduler.development.js:646
runWithPriority$1 @ react-dom.development.js:11276
discreteUpdates$1 @ react-dom.development.js:22413
discreteUpdates @ react-dom.development.js:3756
dispatchDiscreteEvent @ react-dom.development.js:5889`

**Comment by harrisiirak** [comment]
Hi @araskrj1992!

This doesn't look like standard cron syntax (therefore not supported) or something that is widely used/supported. Do you have any link or reference to the service that is generating such cron syntax?

**Comment by Irocktheworld9** [comment]
I want to get the second last day of the month, **0 0 1 L-1 * ?** works in this [https://www.freeformatter.com/cron-expression-generator-quartz.html#cronexpressionexamples](url).
