### ISSUE TITLE
Question about source code

### ISSUE THREAD

**Issue by hehejiuhuizhe** [harrisiirak/cron-parser#232]
Hello, I'm looking into the source code for study, the following code confuses me:
```javascript
CronDate.prototype.addHour = function() {
  var prev = this._date;
  this._date = this._date.plus({ hours: 1 }).startOf('hour');
  if (this._date <= prev) {
    this._date = this._date.plus({ hours: 1 });
  }
};

CronDate.prototype.addMinute = function() {
  var prev = this._date;
  this._date = this._date.plus({ minutes: 1 }).startOf('minute');
  if (this._date < prev) {
    this._date = this._date.plus({ hours: 1 });
  }
};

CronDate.prototype.addSecond = function() {
  var prev = this._date;
  this._date = this._date.plus({ seconds: 1 }).startOf('second');
  if (this._date < prev) {
    this._date = this._date.plus({ hours: 1 });
  }
};
```
When will the _date be less than prev? And why in "addMinute" and "addSecond ", there is "plus({ hours: 1 })"?
May someone help me?

**Comment by harrisiirak** [comment]
Hi @hehejiuhuizhe!

This code is meant to handle DST logic (when clock time moves backwards) and it ensures that we don't generate duplicate date.

Sorry about the delay!
I'll close this issue for now, but don't hesitate to re-open it if you have more questions.

**Comment by hehejiuhuizhe** [comment]
Thanks for your reply!
