### ISSUE TITLE
Parser throws error on valid cron string

### ISSUE THREAD

**Issue by Arkh1** [harrisiirak/cron-parser#233]
We have a valid cron string that is throwing an error when the parser attempts to parse it.
`"0 0/15 * ? * * *"`
Is there something about this cron string that is not supported by this parser?

**Comment by harrisiirak** [comment]
Hi @Arkh1!

https://github.com/harrisiirak/cron-parser#supported-format

```
*    *    *    *    *    *
┬    ┬    ┬    ┬    ┬    ┬
│    │    │    │    │    |
│    │    │    │    │    └ day of week (0 - 7) (0 or 7 is Sun)
│    │    │    │    └───── month (1 - 12)
│    │    │    └────────── day of month (1 - 31, L)
│    │    └─────────────── hour (0 - 23)
│    └──────────────────── minute (0 - 59)
└───────────────────────── second (0 - 59, optional)
```

However, your input contains 7 space separated values/parts.

**Comment by Arkh1** [comment]
Is there any intention to implement year support with 7 value cron strings?

**Comment by harrisiirak** [comment]
See more discussion about year support: https://github.com/harrisiirak/cron-parser/issues/174
There is a fork (based on `2.x` version) that contains 7 segment (and year) support, but no direct ETA for my side to support this functionality in this main version of `cron-parser`.
