### ISSUE TITLE
stringify yields dayOfMonth ranges instead of wildcards

### ISSUE THREAD

**Issue by 2manyvcos** [harrisiirak/cron-parser#239]
When there is only one specific month in an expression, the resulting dayOfMonth array only includes the days that are possible for this month, instead of all possible values (1-31), because of this function: https://github.com/harrisiirak/cron-parser/blob/8568b5093540ee9b5896b55fc40f9d619a7cef7d/lib/expression.js#L368

However, the stringify function does not consider this behavior, so in this situation the output does not have a wildcard as dayOfMonth, but the range of days.

```js
var parser = require("cron-parser")

parser.parseExpression('* * * 2 *').stringify()
// "* * 1-29 2 *"

parser.parseExpression('* * * 4 *').stringify()
// "* * 1-30 4 *"
```

I would expect the result to be "* * * 2 *" instead.

Alternatively, to prevent breaking the existing behavior, it would be also enough for me to have the option of disabling the _handleMaxDaysInMonth function when parsing an expression.

What do you think about this?

Edit: The same goes for CronExpression.fieldsToExpression.

**Comment by harrisiirak** [comment]
@hatsuo thanks for reporting this, I'll investigate this as soon as possible.

> I would expect the result to be "* * * 2 *" instead.

Yep, that should be the correct result. `stringifyField` doesn't have much context awareness and when serialization happens, it's using default constraints (1 - 31). I'm thinking that maybe when explicit month value is provided, we should override day of month constraints.

With default constraints, this code path is never triggered: https://github.com/harrisiirak/cron-parser/blob/master/lib/field_stringify.js#L10-L12

> Alternatively, to prevent breaking the existing behavior, it would be also enough for me to have the option of disabling the _handleMaxDaysInMonth function when parsing an expression.

I would avoid adding option to turn on/off functionality related to usage of `_handleMaxDaysInMonth` - this makes things more complicated.
