### ISSUE TITLE
Running a cron-job every other week

### ISSUE THREAD

**Issue by rinorbytyci** [harrisiirak/cron-parser#240]
Is there a way to do this? E.g. schedule a job every other Wednesday using this library?

**Comment by harrisiirak** [comment]
@rinorbytyci unfortunately `cron-parser` is not supporting such behaviour.

Historically, for some cron implementations this can be achieved as `0 0 1-7,15-21 * 3` but not here. It will match day of week and day of month both. See #173 for more details - shortly, I would like to intend to retain such behaviour (as it looks more like standard expects).
