### ISSUE TITLE
Wrong Date (off by one day) When Looking for 3rd Thursday of the Month at Noon

### ISSUE THREAD

**Issue by jerrens** [harrisiirak/cron-parser#246]
When given the pattern `0 0 12 ? * 5#3`, which according to several online generators should return the 3rd Thursday of the month at noon, the cron-parser module returns the 3rd Friday of the month instead.

```
const pattern = '0 0 12 ? * 5#3';
const cronOptions = {currentDate: new Date(1982,6,10)};

const interval = cron.parseExpression(pattern, cronOptions);
console.log(interval.next().toDate());
// Output: Fri Jul 16 1982 12:00:00 GMT-0400 (Eastern Daylight Time)
// Expected: Thu Jul 15 1982 12:00:00 GMT-0400 (Eastern Daylight Time)
```

**Comment by harrisiirak** [comment]
@jerrens Hi!

> which according to several online generators should return the 3rd Thursday of the month at noon

Do you have any example?

> the cron-parser module returns the 3rd Friday of the month instead.

But this is what `5#3` defines, right? If you want Thursday, you should use `4#3`.

**Comment by jerrens** [comment]
@harrisiirak Hello!

The online generators that I tried were:
https://www.freeformatter.com/cron-expression-generator-quartz.html
https://crontab.cronhub.io/

However, I just found another one today that matches your thoughts though - that 5#3 represents the 3rd Friday:
http://www.cronmaker.com/

Perhaps this is just a case where some programming languages represent Sunday = 1 and other have Monday = 1

It looks like some have resolved this problem by using the abbreviation for the day in the pattern instead of a number: `0 0 12 ? * THU#3`

**Comment by harrisiirak** [comment]
@jerrens in cron standard, day of week is defined as 0–6, where SUN=0 SAT=6 (`cron-parser` also supports 7 as SUN).
