### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by chenGITHUB123** [harrisiirak/cron-parser#247]
\lib\expression.js

 if (atoms.length > 6) {
       throw new Error('Invalid cron expression');
     }

why right like this?

**Comment by chenGITHUB123** [comment]
it go wrong when the cron-expression like this '0 * * * * ? *'
when i remove the code ,it is right

**Comment by harrisiirak** [comment]
@chenGITHUB123 Hi! What do you exactly want to achieve by removing this code block? This is part of the patter validation.

**Comment by chenGITHUB123** [comment]
> @chenGITHUB123 Hi! What do you exactly want to achieve by removing this code block? This is part of the patter validation.

when i got some cron-expression on this website(https://cron.qqe2.com/), i copy it to my code ,but it cannot be checked by this cron-parser, it throw new Error('Invalid cron expression')

**Comment by harrisiirak** [comment]
Still not completely sure what do you exactly try to achieve here as `cron-parser` is supporting 5 + 1 schema (standard unix format + seconds).
Supported format: https://github.com/harrisiirak/cron-parser#supported-format

**Comment by chenGITHUB123** [comment]
> Still not completely sure what do you exactly try to achieve here as `cron-parser` is supporting 5 + 1 schema (standard unix format + seconds). Supported format: https://github.com/harrisiirak/cron-parser#supported-format

ok, i got it . it does not surport 'year'.Thanks for your help.

**Comment by harrisiirak** [comment]
No problem!

**Comment by zhangtengjin** [comment]
> No problem!

Hello, excuse me, why not support 'year'?
