### ISSUE TITLE
依赖项使用的版本有问题

### ISSUE THREAD

**Issue by zlightm** [harrisiirak/cron-parser#248]
luxon@1.28.0->esdoc@1.1.0->minimist@1.2.0
minimist是一个解析参数选项模块。
此软件包的受影响版本（1.2.0）容易受到原型污染。
库可能会被诱骗使用构造函数或proto有效负载添加或修改Object.prototype的属性。

**Comment by harrisiirak** [comment]
Hi @zlightm!

Could you elaborate where you're seeing such warning? And also, previously (when this issue was created) we're using `luxon@1.26.0`, now it's upgraded to `luxon@1.28.0` and I'm not seeing such warning.

**Comment by zlightm** [comment]
是我们公司的测试扫描包版本，我大概看了下是luxon的devDependencies里面使用了esdoc，我们现在用别的办法暂时解决了一下(把包下下来删除这个依赖重新编辑)，但是不是长久之计，所以之前给你们提了一个issues。
