### ISSUE TITLE
Serializing an expression into a human-readable string

### ISSUE THREAD

**Issue by kotx** [harrisiirak/cron-parser#250]
E.g. [cron helper](https://cron.help/#*/5_*/12_*_*_*) turns `*/5 */12 * * *` into `Every 5 minutes during 12am and 12pm`. This would be useful for user input so they know they haven't messed up.

**Comment by PranavKuAn** [comment]
@kotx [cronstrue](https://github.com/bradymholt/cronstrue) does exactly this.

**Comment by kotx** [comment]
yeah, I found that but it seems the way cron-parser parses cron entries is different from cronstrue.

**Comment by harrisiirak** [comment]
Currently there is no plan to support serializing an expression into a human-readable string. Closing it for now.
