### ISSUE TITLE
Seems like 7L option does not work 

### ISSUE THREAD

**Issue by githubajay1mishra** [harrisiirak/cron-parser#259]
When i enter a cron expression `* * * * 7L`, parseExpression api `result.hasNext()` is false.

0-7 seems to work fine. With 0 and 7 being Sunday and 1 being Monday ....
0L-6L seems to work fine With 0L being last Sunday and 1L being Monday 
But when i use 7L, does not really give back last Sunday of the month

**Comment by harrisiirak** [comment]
@githubajay1mishra thanks for reporting this issue, it looks like abug.

[This line](https://github.com/harrisiirak/cron-parser/blob/master/lib/expression.js#L533) it's not taking account/not supporting 7 as weekday when `L` is used.
