### ISSUE TITLE
month 12 invalid range error

### ISSUE THREAD

**Issue by fazza4613** [harrisiirak/cron-parser#261]
When i parse 0 0 0 1 12/1 * i received this error: 
**core.js:6014 ERROR Error: Invalid range: 12-12
    at parseRange**

i think for this code of expression.js 
```
else if (min >= max) {
        throw new Error('Invalid range: ' + val);
      }
```
at line 327.

I receveid the same error when passing 0 0 0 1 13/1 * but in this case is correct because the range is 1-12

**Comment by harrisiirak** [comment]
Hi @fazza4613!

This the same case as https://github.com/harrisiirak/cron-parser/issues/188. As mentioned this before, not definitely standard behaviour, but something that still could be supported.

**Comment by harrisiirak** [comment]
Currently closing this in favour of https://github.com/harrisiirak/cron-parser/issues/188 (duplicate).
