### ISSUE TITLE
Should validate repeat string baisc format

### ISSUE THREAD

**Issue by zangguodong** [harrisiirak/cron-parser#262]
https://github.com/harrisiirak/cron-parser/blob/f687555f25ff0e4e12a951f3a4827b382436692f/lib/expression.js#L275

Due to not providing basic repeat atomic format validation, cron-parser sees format like
`10 16/17/18 * * *`
as valid, and parse it as  `10 16/17 * * *`. But `16/17/18` should not be correct format, isn't it?

<img width="544" alt="image" src="https://user-images.githubusercontent.com/29418459/160323893-2009494b-df96-4bc2-9036-52ab6c28e9d5.png">

**Comment by harrisiirak** [comment]
@zangguodong thanks for reporting this! It should throw an error indeed as it's in an invalid format.
