### ISSUE TITLE
prev() is skipping the nearest event if it happened today

### ISSUE THREAD

**Issue by amiram** [harrisiirak/cron-parser#265]
When the cron represents a weekday and it happened today, prev() first event is a week before today.
Test that shows that:
```
test('prev test', function(t) {
  var options = {
    currentDate: new Date('2022-04-06T23:30:00.000Z'),
  };

  var interval = CronExpression.parse('0 0 11 ? * 4', options);
  var prev = interval.prev();
  t.equal(prev.getMonth(), 3);

  t.end();
});
```

Unless you set the currentDate to 04-07, prev always return 03-31.

**Comment by harrisiirak** [comment]
Hi @amiram!

Your cron expression translates to: `At 11:00 on Thursday.`

However `currentDate: new Date('2022-04-06T23:30:00.000Z')` (April of 6th) is Wednesday and when call `prev()` then indeed closest Thursday will be on Match of 31.

**Comment by amiram** [comment]
Thanks @harrisiirak . Looking here https://www.freeformatter.com/cron-expression-generator-quartz.html I see that it translates to "At 11:00:00am, on every Wednesday, every month", not Thursday.

**Comment by harrisiirak** [comment]
@amiram it's rather strange, and definitely not part of "classical standard". Day of week is usually in range 0-6 (or SUN–SAT), therefore 4 stands always for Thursday, not Wednesday. This is also described [here](https://github.com/harrisiirak/cron-parser#supported-format).

**Comment by amiram** [comment]
It looks like you're right. I'll have to convert the value we're using since we use Amazon EventBridge and it is using 1-7. From Wikipedia: `The Amazon EventBridge implementation of cron does not use 0 based day of week, instead it is 1-7 SUN-SAT (instead of 0-6), as well as supporting additional expression features such as first-weekday and last-day-of-month.`

**Comment by harrisiirak** [comment]
@amiram can we close this one?
