### ISSUE TITLE
got errors in vite

### ISSUE THREAD

**Issue by rashagu** [harrisiirak/cron-parser#275]
```
  The plugin "vite:dep-pre-bundle" was triggered by this import

    ../../node_modules/.pnpm/cron-parser@4.5.0/node_modules/cron-parser/lib/parser.js:106:10:
      106 │   require('fs').readFile(filePath, function(err, data) {

```

**Comment by harrisiirak** [comment]
Hi @rashagu,

Doesn't seem directly related to this library but can you please some example how you using cron-parser over there?

**Comment by neelkarma** [comment]
I think that error is happening because you're trying to use `cron-parser` in a browser environment - and browsers don't support node-only modules like `fs`.
