### ISSUE TITLE
Cron expressions "Every 2, 3, 4, 5, 6 months" aren't working properly when currentDate is set

### ISSUE THREAD

**Issue by gentledev** [harrisiirak/cron-parser#278]
Steps to reproduce:

  
    var cronExpression = "0 0 20 */6 *";  //  Every 6 months (At 00:00 on day-of-month 20 in every 6th month)

    // All of these "currentDates" generate the same wrong next dates starting from January.
    var options = {
      currentDate: '2022-02-20 00:00:00',
      //currentDate: '2022-03-20 00:00:00',
      //currentDate: '2022-04-20 00:00:00',
      //currentDate: '2022-05-20 00:00:00',
      //currentDate: '2022-06-20 00:00:00',
    };
    
    try {
      var interval = cronParser.parseExpression(cronExpression, options);
      console.log(interval.next().toString());   // Wed Jul 20 2022 00:00:00 GMT+0200
      console.log(interval.next().toString());   // Fri Jan 20 2023 00:00:00 GMT+0100
      console.log(interval.next().toString());   // Thu Jul 20 2023 00:00:00 GMT+0200
      console.log(interval.next().toString());   // Sat Jan 20 2024 00:00:00 GMT+0100
      console.log(interval.next().toString());   // Sat Jul 20 2024 00:00:00 GMT+0200
    } catch (err) {
      console.log('Error: ' + err.message);
    }

**Comment by harrisiirak** [comment]
Hi @gentledev!

Can you explain what is exactly wrong with generated date values+ Based on described outputs, behaviour looks expected.

`*/6` translates as `1-12/6` which means that January/July both are considered as every 6 moths. And matching is absolute based on the values in the range. If you set iteration start date as `'2022-02-20 00:00:00'` then next possible match will be in July (and after that January).

[This](https://stackoverflow.com/a/27412884/143788) is rather good SO post that explains how cron steps are working. 

And Wikipedia has also a good explanation:

> For example, */5 in the minutes field indicates every 5 minutes (see note below about frequencies). It is shorthand for the more verbose POSIX form 5,10,15,20,25,30,35,40,45,50,55,00.

**Comment by gentledev** [comment]
Thanks so much for the explanation.

The problem wasn't this library. There isn't any cron expressions for doing what I wanted.

FOR INFORMATION PURPOSES, the closest cron expression would include the month list generated by a function providing the step and the starting month.
Here is an example:

```
  function generateMonthList(step, month){
    // The step must be a 12 divisor (2,3,4,6)
    return Array(12 / step).fill().map((x, i) =>(month + step*i)%12 || 12).join(",");
  }

  // Generate the cron expression "every 6 month from month 3"
  // This will output the following cron expression: 0 0 1 3,9 *
  console.log(`0 0 1 ${generateMonthList(6, 3)} *`)
```

Warning: This function can't handle 29, 30, or 31  day-of-month, and thinking about what I wanted to do I decided to restructure the whole flow with a different logic by running a single cron job every day.
