### ISSUE TITLE
是不是不支持 typescript 4.1+    能不能添加 支持

### ISSUE THREAD

**Issue by yanwuguangjun** [harrisiirak/cron-parser#281]
是不是不支持 typescript 4.1+    能不能添加 支持

**Comment by harrisiirak** [comment]
Hi @yanwuguangjun!

Documentation was out of date and this library actually requires version `>= 4.2`. Updated in https://github.com/harrisiirak/cron-parser/commit/fefd0a23f334fa0120d619951c3e5900be8cd37e
