### ISSUE TITLE
8 days in a week?

### ISSUE THREAD

**Issue by AlanMcKen** [harrisiirak/cron-parser#302]
Hi, 
	
Did I miss something and now there are eight days in the week?	

0 */15 * ? * *
"dayOfWeek":[0,1,2,3,4,5,6,7]

**Comment by harrisiirak** [comment]
Hi @AlanMcKen,

Please see supported format section: https://github.com/harrisiirak/cron-parser#supported-format

> day of week (0 - 7, 1L - 7L) (0 or 7 is Sun)

Best regards
