### ISSUE TITLE
Use es6 modules (error: module undefined)

### ISSUE THREAD

**Issue by jehon** [harrisiirak/cron-parser#308]
When using "

`import * from './node_modules/cron-parser/lib/parser.js'`

I receive an error:

```
  ReferenceError: module is not defined
  @node_modules/cron-parser/lib/parser.js:116:1
```

This is due (and normal) to the module.exports = ... which is a legacy syntax.

Would it be possible to migrate to es6 import/export? That would certainly need a major version...

**Comment by harrisiirak** [comment]
Hi @jehon!

Do you have any isolated example that helps to reproduce this issue. Currently `cron-parser` should play well with ES6 modules.

Best regards
