### ISSUE TITLE
fields.dayOfWeek = [1,3,5] generates incorrect cron expression 

### ISSUE THREAD

**Issue by klumba12** [harrisiirak/cron-parser#310]
example: https://stackblitz.com/edit/typescript-playground-spjybj?file=index.ts

```typescript
const at10amMonWenFri = parser.parseExpression('0 0 10 * 1,3,5');
const cron = parser.fieldsToExpression(at10amMonWenFri.fields).stringify(true);

// expected origin 0 0 10 * 1,3,5
// but cron equals to 0 0 10 * 1/2 
// when dow is 1/2  - Sundays are included in the generated dates
console.log(cron);
```

**Comment by abberadhi** [comment]
Hey, I can confirm I experience this issue as well.

**Comment by harrisiirak** [comment]
Hi @klumba12 and @abberadhi!

Thanks for reporting and confirming this. It seems to be caused by the bugfix in #295. I'll revisit this and see if there is better fix for initial bug.

Best regards

**Comment by harrisiirak** [comment]
@klumba12 and @abberadhi created a quick fix Draft-PR: https://github.com/harrisiirak/cron-parser/pull/312
Let me know how it working for you. Shortly, stringify should now retain original value where needed and only optimise multiple values based field when it makes sense.

**Comment by klumba12** [comment]
hi @harrisiirak, looks great! thank you

**Comment by d00rsfan** [comment]
Hi!
 It still looks bug with cron string `0 0 ? * */2`
 .prev must return February, 27 but it returns this midnight: March, 5.
 so with .next: it returns midnight March, 7.
 Not sure if it the same bug or diffirent.
 How did i reproduce:
 0. in root of current project, npm uninstall cron-parser
1. git clone https://github.com/harrisiirak/cron-parser.git
2. cd cron-parser/
3. git checkout fix/stringify-range-step-handling
4. npm i
5. fix `import cronParser from '../../cron-parser/lib/parser.js';`

----
P.S. is it correct way to test with branche? just `npm install https://github.com/harrisiirak/cron-parser#fix/stringify-range-step-handling`
