### ISSUE TITLE
Example in README is incorrect

### ISSUE THREAD

**Issue by haneefkassam** [harrisiirak/cron-parser#311]
In the README.md, the examples provided in the "Last weekday of the month" section are incorrect, and lead to some confusion.

The README indicates that "the cron expression to run on the last monday of the month at midnight" is "0 0 * * * 1L".  However, since this is a 6-element cron expression, what this really represents is "every hour, on the hour, on the last monday of the month".

To run on the last monday of the month at midnight, the expression in the example needs 1 more 0, so "0 0 0 * * 1L".

It's not clear, but the second example in that section may also need this additional 0 (it doesn't specify the time).

**Comment by harrisiirak** [comment]
Hi @haneefkassam!

Thanks for reporting this. You're correct indeed.

Best regards
