### ISSUE TITLE
cron expression does not match result

### ISSUE THREAD

**Issue by YingJian-hu** [harrisiirak/cron-parser#325]
Today is Friday, May 26, when I set the corn expression to "0/30 * * * 5 4" (I want to represent the next Thursday in May), the result time is May 2 next year

corn：
console.log('parseExpression: ', parseExpression("0/30 * * * 5 4").next().toString())

expectation：
2023/06/01 HH:mm:ss

result:
2024/05/02 HH:mm:ss (Thu May 02 2024 00:00:00 GMT+0800)

additional：

"0/30 * * * 5 3" is normal，it appears as "2023/05/23 HH:mm:ss"

**Comment by harrisiirak** [comment]
Hi @YingJian-hu!

> (I want to represent the next Thursday in May), the result time is May 2 next year
> expectation：
2023/06/01 HH:mm:ss

Your expression state: `At every second and every 30th minute on Thursday in May.` That expectation can't happen as `2023/06/01` is already in June and next possible match to your expression is in next year.

Best regards

**Comment by YingJian-hu** [comment]
Thank you, I didn't understand at first, my fault
