### ISSUE TITLE
”0 0 22 * * ? * “ parser cron expression error

### ISSUE THREAD

**Issue by Leowuqunqun** [harrisiirak/cron-parser#330]
![image](https://github.com/harrisiirak/cron-parser/assets/11615263/45e386e6-c23e-42f8-9992-6cf0ee8aa203)

**Comment by harrisiirak** [comment]
Hi @Leowuqunqun!

This error says what it says. Please check your input pattern and see https://github.com/harrisiirak/cron-parser#supported-format

Best regards
