### ISSUE TITLE
:bug: the cron time is error

### ISSUE THREAD

**Issue by xing403** [harrisiirak/cron-parser#332]
When I set cron to `0 * * * * *`, normal execution should execute the required function in 0 seconds of every minute, but it is actually every 20 seconds. 

When I set the cron to `*/20 * * * * *`, I didn't find a change in the interval between two times, so I don't know if it was the problem with my configuration or the warehouse.

![image](https://github.com/harrisiirak/cron-parser/assets/74746021/541d8005-aec5-41a4-94ad-65bff24e4389)

![image](https://github.com/harrisiirak/cron-parser/assets/74746021/d638f7ab-1ee1-4f9e-b995-416aceccaf4a)

**Comment by harrisiirak** [comment]
Hi @xing403!

You seem to be using some 3rd party software along `cron-parser`. Tested this provided cron expression in the isolation and don't see this happening. Please provide standalone example (only `cron-parser` related code) that can be used to reproduce the issue.

Best regards
