### ISSUE TITLE
The crontab expression '0 0 0 12W 6' is causing a parsing error

### ISSUE THREAD

**Issue by XingChenGod** [harrisiirak/cron-parser#334]
```js
var parser = require('cron-parser');

try {
  // 0 0 0 LW * ?    Trigger at midnight on the working day closest to the 12th day of June
  // 0 0 0 12W 6 *   Trigger at midnight on the last working day of each month.
  var interval = parser.parseExpression('0 0 0 12W 6 *');
} catch (err) {
  console.log('Error: ' + err.message);
}
```
errorInfo：
Error: Invalid characters, got value: LW
Error: Invalid characters, got value: 12W

**Comment by harrisiirak** [comment]
Hi @XingChenGod!

Please read the documentation about the supported format: https://github.com/harrisiirak/cron-parser#supported-format
Also an open feature request: https://github.com/harrisiirak/cron-parser/issues/167

Best regards
