### ISSUE TITLE
[Docs]: API for Composing Cron Strings

### ISSUE THREAD

**Issue by mahyarmirrashed** [harrisiirak/cron-parser#337]
Hi there, I developed the [`cron-compose`](https://github.com/mahyarmirrashed/cron-compose) library. The purpose of the library is to expand accessibility to Cron for people that might not be as technically savvy with Cron. If you feel that this library is something that you support, I would be really grateful if you could mention it at the bottom of your README. Ciao!

**Comment by harrisiirak** [comment]
Hi @mahyarmirrashed!

Your library looks neat but there is currently no plan to add 3rd party library links to the documentation.

Best regards
