### ISSUE TITLE
Hangs finding invalid values

### ISSUE THREAD

**Issue by ncb000gt** [harrisiirak/cron-parser#34]
I'm considering using this module to replace the CronTime code in the `cron` project. However, one of my tests is failing to do anything because this module runs into the same issue that my CronTime code used to. I'm sharing the issue here so that you can take a look at what I did and see if it works for you or in case you have a better alternative.

https://github.com/ncb000gt/node-cron/issues/79

I wont be able to use this module until this is fixed as I don't want to expose any regressions my module. :) Thanks for taking a look.

**Comment by harrisiirak** [comment]
Hello! I'll look into this soon as possible. Thank you for reporting! :)

**Comment by ncb000gt** [comment]
No problem. My "fix" was really a bandaid where I didn't allow the module to hang and just threw an error regarding the faulty value.

Another option would be to check the dates to see if they exist and force them to whatever the maxes are. For instance, if someone specifies a date of `1/99/2015` just scale it back to 31 for the month of January and then warn them of this as well.

Anyway, thanks!

**Comment by harrisiirak** [comment]
At the moment it's throwing an exception when one of the fields is out of the range. Usually this "strict mode" is good and gives a feedback to the user when something funky is going on with input pattern.

I don't have any plans to change this behaviour in current (0.6) minor version branch, but I had plans to add some non-standard cron features (like L, W etc.) in the next minor release (0.7), which can be enabled by specific flags. That date auto-scaling feature also seems to be nice addition.

**Comment by harrisiirak** [comment]
@ncb000gt can I close this one?
