### ISSUE TITLE
First Monday of each month triggers every day

### ISSUE THREAD

**Issue by lorem--ipsum** [harrisiirak/cron-parser#341]
Hey, first of all thank you for this great library :-)

I think this string is incorrectly parsed: `0 0 8 */100,1-7 * 1`. According to [this cronTab guru](https://crontab.guru/#0_8_*/100,1-7_*_1), it should match the first Monday of every month, because of some weirdness of Cron explained [here](https://blog.healthchecks.io/2022/09/schedule-cron-job-the-funky-way/).

Unfortunately cron-parser doesn't seem to work with it and triggers every day. Here's a minimal test to replicate this:

```
const now = new Date('2023-12-04T00:00:00.000Z');

const interval = cron.parseExpression('0 0 8 */100,1-7 * 1', {
  currentDate: now,
  tz: 'UTC',
});

// first Monday of next month is the 1st of January
expect(interval.next().toDate().toISOString()).toBe('2024-01-01T08:00:00.000Z');

// then first Monday of month after is the 5th of February
expect(interval.next().toDate().toISOString()).toBe('2024-02-05T08:00:00.000Z');
```

I hope I didn't miss something obvious! Thanks

**Comment by harrisiirak** [comment]
Hi @lorem--ipsum 

Thanks for reporting this!

> Unfortunately cron-parser doesn't seem to work with it and triggers every day. 

Yes, you're correct and this is currently also intended way. There is currently no plan to support this linux cron funky behaviour.

Best regards
