### ISSUE TITLE
how to express 'every tow weeks on monday'

### ISSUE THREAD

**Issue by ilaipi** [harrisiirak/cron-parser#342]
`0 0 0 * * 1`

this is every monday morning.

how about the every two weeks?

**Comment by harrisiirak** [comment]
Hi @ilaipi!

This is currently not supported. Even with Linux system cron (see [this](https://stackoverflow.com/questions/46109358/how-to-create-a-cron-expression-for-every-2-weeks) interesting discussion), you need to use clever workaround(s) to get it somehow working.

Still, something interesting to consider in the future, but closing it for now.
