### ISSUE TITLE
Possible bug or a misunderstanding

### ISSUE THREAD

**Issue by briangleeson** [harrisiirak/cron-parser#346]
Versions tested: `2.18.0` and `4.9.0` 

Using the expression `"0 19 22 3 5"` I expected this to match today "Friday 22nd March 2024" and then the next occurence would be in 6 years on "Friday 22nd March 2030", which is the next occurence of a Friday falling on the 22nd of March. Instead it matches for any Friday in March, ignoring the "22 day of the month" piece. Is my understanding here correct?

Output:
```
const interval = parser.parseExpression("0 19 22 3 5");

Date:  Fri Mar 22 2024 19:00:00 GMT+0000
Date:  Fri Mar 29 2024 19:00:00 GMT+0000
Date:  Fri Mar 07 2025 19:00:00 GMT+0000
Date:  Fri Mar 14 2025 19:00:00 GMT+0000
```

My expectation:
```
const interval = parser.parseExpression("0 19 22 3 5");

Date: Fri Mar 22 2024 19:00:00 GMT+0000
Date: Fri Mar 22 2030 19:00:00 GMT+0000
Date: Fri Mar 22 2041 19:00:00 GMT+0000
Date: Fri Mar 22 2047 19:00:00 GMT+0000
```

**Comment by harrisiirak** [comment]
Hi @briangleeson!

If I'm not skipping over the lines, this is still expected behaviour. Read more: https://github.com/harrisiirak/cron-parser/issues/173#issuecomment-537460642

Based on this,  your expression translates to:

> on day-of-month 22 and on Friday in March

Best regards

**Comment by briangleeson** [comment]
@harrisiirak ok thanks for the clarification, I guess I should just RTFM 😄
