### ISSUE TITLE
00 1/8 * * * *

### ISSUE THREAD

**Issue by syq1122** [harrisiirak/cron-parser#351]
Why does parseExpression pass the verification when the day and week are * at the same time, for example: 00 1/8 * * * *

**Comment by harrisiirak** [comment]
Hi @syq1122!

Could provide more details what is the use case and unexpected behaviour here? The pattern you provided, works as expected. Also * are valid symbols for day of week and day of month fields.

Best regards

**Comment by syq1122** [comment]
Expression 00 1/8 * * * * in http://cron.jsrun.net/ Unable to verify, but cron Parser can verify

**Comment by syq1122** [comment]
> Hi @syq1122!
> 
> Could provide more details what is the use case and unexpected behaviour here? The pattern you provided, works as expected. Also * are valid symbols for day of week and day of month fields.
> 
> Best regards


Expression 00 1/8 * * * * in http://cron.jsrun.net/ Unable to verify, but cron Parser can verify

**Comment by harrisiirak** [comment]
Yes, this is expected and supported use case by `cron-parser`.
