### ISSUE TITLE
日期W无法被解析

### ISSUE THREAD

**Issue by rookiecdn** [harrisiirak/cron-parser#354]
import cronParser, {CronExpression} from 'cron-parser';
import dayjs from "dayjs";

export default function getNextFiveExecutions(cronExpression: string): Date[] {
    const options: cronParser.Options = {
        currentDate: new Date(),
        endDate: new Date('2050-12-31T23:59:59'), // 设定一个足够远的未来时间作为结束时间
        iterator: true
    };

    const interval = cronParser.parseExpression(cronExpression, options);

    const executions: Date[] = [];
    for (let i = 0; i < 5; i++) {
        const nextExecution = interval.next();
        if (nextExecution) {
            const datetime = dayjs(nextExecution.value).format("YYYY-MM-DD HH:mm:ss")
            executions.push(datetime);
        }
    }

    return executions;
}
const cronExpression = "0 0 0 1W * ?"
getNextFiveExecutions(cronExpression )  // 报错提示 Error: Invalid characters, got value: 1W

**Comment by harrisiirak** [comment]
Hi @rookiecdn!

Not sure if I understand your issue properly, but W character is not supported at the moment. See supported format: https://github.com/harrisiirak/cron-parser?tab=readme-ov-file#supported-format

Also related feature request: https://github.com/harrisiirak/cron-parser/issues/167

Best regards
