### ISSUE TITLE
Feature Request: Previous interval

### ISSUE THREAD

**Issue by lightswitch05** [harrisiirak/cron-parser#48]
I'm using cron-parser to write an archiving tool. A given cron expression determines in what intervals files get archived. Right now I'm saving the archive file using the archive-creation date, but it would be really nice if there were a way to get the previous interval.

For example, if I created files yesterday (Nov 4th), and I archived them daily `0 0 * * *` then my resulting archive would be named `archive_2015-11-5.tar.bz2`. While Nov. 5th describes the date the archive was created, it doesn't describe the contents of the archive. If there were a way to get the previous interval, I could create archives named `archive_2015-11-4_to_2015-11-5.tar.bz2`.

Is getting the previous interval a feature that fits `cron-parser`?

**Comment by harrisiirak** [comment]
Hey @lightswitch05!

I had some thoughts about that functionality before, but I really haven't had chance to work on it or had practical need for that functionality. 

Your example actually makes sense. Theoretically it should be doable, but I need some time to investigate possible changes and regressions.

BR,
Harri

**Comment by manish-alphonso-tv** [comment]
I need. this as well. I am using **cron** and **cron-parser** it to write a scheduler which can keep a job running between two cron job specs, e.g. every day **from** 5pm **to** 6pm. or **from** Monday 1pm **to** Tuesday 5am. 

My need is when my scheduler starts, I need to know if the 'current' date/time falls between job's date/time range (i.e. between job.from and job.to). To figure that out, I need to know the 'previous' interval for job's **from** specs.

**Comment by owenallenaz** [comment]
I have a similar need in this case. I was wondering if it would be possible to have reset() take an optional Date object. If passed, it would simply reset it to that date in time. It seems like that would a few lines of code and would provide for mine and the above use-cases.
