### ISSUE TITLE
Add browser support

### ISSUE THREAD

**Issue by bvaughn** [harrisiirak/cron-parser#49]
The `parseExpression` function could be useful for browser-based users. Unfortunately, importing the library via webpack causes an error:

```
ERROR in ./~/cron-parser/lib/parser.js
Module not found: Error: Cannot resolve module 'fs' in /path/to/project/node_modules/cron-parser/lib
 @ ./~/cron-parser/lib/parser.js 93:2-15
```

Would you be willing to package this in such a way as to either expose `CronExpression.parse` or allow the `parseExpression` to be used without triggering the import?

**Comment by kusold** [comment]
I think webpack may be doing something weird here. `fs` is only required inside of the `parseFile` function. I have successfully used this package on the client side with `component` and `browserify`.

**Comment by bvaughn** [comment]
Gotcha. I think the Webpack static analysis in 1.x isn't that great.
Guess I'll close this issue though as it doesn't really seem like your problem.
Thanks for the speedy response.

**Comment by bvaughn** [comment]
Actually, re-opening this issue with a potential (easy) solution for you to consider. Webpack and Browserify support the following approach:
https://gist.github.com/defunctzombie/4339901#replace-specific-files---advanced

This means that if you'd be willing to add the following to your `package.json`...
```json
  "browser": {
    "fs": false
  }
```
...then Webpack 1.x users wouldn't be burned by the static analysis issue I originally reported. I've tested this change with a local copy of your library and it resolves my issue.

I'll submit a PR shortly for your consideration. :)

**Comment by bvaughn** [comment]
Thanks for accepting the PR! Any chance we could get a `1.0.2` release with this updated package JSON? :)

**Comment by harrisiirak** [comment]
@bvaughn np, done.

**Comment by bvaughn** [comment]
Thanks again! :)
