### ISSUE TITLE
next() no longer returns a Date

### ISSUE THREAD

**Issue by owenallenaz** [harrisiirak/cron-parser#58]
In previous versions next() used to return a Date, now it returns a CronDate. I was wondering if that change was done with intent or was accidental.

If it was intentional then I have a couple possible ideas:

1. From looking at the code it appears that date.js is basically just a proxy to moment(), my question is why not just cut out the middle-man, eliminate date.js and have next() actually return the moment? Moment is a fairly well documented library and most devs know how to interact with it. If next() returned a moment() it would be simple to get to the raw date value by just doing moment's toDate() and since it's a moment obj I have access to all of the various methods and features that moment has.

2. If you don't want to expose the moment dependency, then I would propose adding a toDate() to CronDate that proxies to moments() toDate() so that we can get access to the Date obj. In the old version when it returned date objects this wasn't necessary, but now that it does I end up needing to do awkward things like `new Date(interval.next().toString()` in order to get the date obj.

**Comment by harrisiirak** [comment]
@owenallenaz yes, that change was introduced in latest version `2.0.0` as part of timezone handling improvements. 

I would rather like to retain current CronDate abstraction as it provides compatibility (well yes, currently only partially) for Date class API. Sorry that documentation didn't reflect all the latest changes.

So what I'm going to do:

- Expose `toDate()` (`2.0.1`)
- Add missing Date class API methods (`2.1.0`)
- Improve documentation (`2.1.0`)

Thanks for the feedback!

**Comment by santigimeno** [comment]
I think it's a good idea. In fact I think I had a `toDate()` method for some time when I was developing the functionality.

**Comment by santigimeno** [comment]
Sorry for being too picky, but shouldn't the `toDate()` addition have been a `semver-minor` instead of a `semver-patch` change?
