### ISSUE TITLE
.validate() method

### ISSUE THREAD

**Issue by dr-dimitru** [harrisiirak/cron-parser#61]
Does this library has a `.validate()` method (*to validate passed string, as eligible CRON instruction*)?

**Comment by harrisiirak** [comment]
@dr-dimitru `parse()` is actually throwing an exception if the expression is in invalid format.

**Comment by dr-dimitru** [comment]
Okay, then take it as feature suggestion to add `.validate()` or `.isValid()` method. 
I can PR this feature, if you're agree with me. Tell me which method name is more convenient for this lib and I will send a PR
