### ISSUE TITLE
next() on newly parsed expression returning past value

### ISSUE THREAD

**Issue by owenallenaz** [harrisiirak/cron-parser#62]
We have a job that runs every minute, and it causes an issue where parseExpression() will return a job whose first run time is actually in the past. Here's a simply reproduction:

```js
var cron_parser = require("cron-parser");
var minuteStart = new Date(cron_parser.parseExpression("* * * * *").next().toString());

setTimeout(function() {
	console.log(Date.now());
	
	console.log(new Date(cron_parser.parseExpression("* * * * *").next().toString()).getTime());
}, minuteStart - new Date());

// result
1459566240061 - now
1459566240000 - next run time, in the past???
```

From the output you can see that the first console.log of what time it is now and the parseExpression that occurs after it yet has a date stamp preceding what time it actually is. The only way i'm able to consistently get this to happen is in conjunction with a setTimeout that puts my node instance right around the minute point. At first I thought possible Node was firing the setTimeout prior to the timeout value, but from my tests this is not the case. This is occurring on Node 5.9.0.

**Comment by harrisiirak** [comment]
@owenallenaz sorry about the delay... gonna look this later.

**Comment by JohnyDays** [comment]
When you convert a date to a string you lose millisecond precision, that is why this happens

**Comment by JohnyDays** [comment]
correct code would be 
```javascript
console.log(Date.now());

console.log(new Date(cron_parser.parseExpression("* * * * *").next().getTime()));
```
