### ISSUE TITLE
System time is used as currentDate when supplying value 0

### ISSUE THREAD

**Issue by themaarten** [harrisiirak/cron-parser#64]
Cron-parser ignores the supplied `currentDate` and falls back to the system time for the options object below.
```javascript
options = {
    currentDate: 0 // 1970-01-01T00:00:00.000Z
}
```

[Line 610 of expression.js](https://github.com/harrisiirak/cron-parser/blob/master/lib/expression.js#L610) causes this problem. It test falsyness where it should test for `undefined` or `null`.

**Comment by harrisiirak** [comment]
@themaarten a good point. Going to improve this soon.
