### ISSUE TITLE
setters on CronExpression

### ISSUE THREAD

**Issue by lancecarlson** [harrisiirak/cron-parser#67]
Do you think this might something you'd consider? At the moment I have to manage the cron string (which is fine) but it seems like it would be more elegant if this library allowed you to set the hour or day and get back the toString() version of the CronExpression.

**Comment by lancecarlson** [comment]
Timezone considerations would be nice/interesting too.

**Comment by harrisiirak** [comment]
I got your point but this rather sounds like a separate module, which handles that abstraction and generates a valid cron string as the result.

**Comment by lancecarlson** [comment]
Would be a pretty tiny module. Pretty easy to do myself, but would be nice if this module did it for me! Wouldn't add much to the API or size of the project.
