### ISSUE TITLE
Does not support '0/2 * * * *'?

### ISSUE THREAD

**Issue by panxue** [harrisiirak/cron-parser#74]

**Comment by harrisiirak** [comment]
@panxue see #21

**Comment by harrisiirak** [comment]
@panxue didn't find anything about that from cron's spec. Anyhow, the correct format is `*/2 * * * *`.

**Comment by panxue** [comment]
sorry, i mean ' 0-59/2 * * * * '

**Comment by harrisiirak** [comment]
@panxue what do you exactly mean by "does not support"? I'm testing this locally and it's working as expected.

**Comment by panxue** [comment]
I want to achieve '0-59/2 * * * *', but choose the wrong expression.
sorry, my fault.
