### ISSUE TITLE
To modify cron expression from one timezone to UTC

### ISSUE THREAD

**Issue by jrphub** [harrisiirak/cron-parser#76]
I need something like this:

> newCronExpression = convert (oneCronExpression, fromTimezone, "UTC")

Let me give you one example:

My local timezone is IST i.e. GMT+5.30.

Current local time is: 11:20 AM.

I want a job to run in 45 min of every hour.

So, my cron expression: 45 * * * *

Hence I am expecting my job to run after 25 min ( as starting time is 11:45 AM)

but my job is running as per UTC.

Current time in UTC : 05:50 AM

As per cron expression 45 * * * , the starting time will be 06:45 AM at GMT.

So, the job will be actually started after 55 min.

**Expected** : After 25 min

**Actual** : After 55 min

So,

> if I am converting my local cron expression 45 * * * to 15 * * * * at GMT, then actual waiting period will be same as expected.
> 
> The question is how will I convert my local cron expression to GMT for all usecase

Is this possible by using your library.

**Comment by santigimeno** [comment]
@jrphub does this work for you?

```js
'use strict';

const cron = require('cron-parser');
const moment = require('moment-timezone');

const date = moment(new Date('Mon Oct 17 2016 11:20:00 GMT+0530')).tz("Asia/Kolkata");

console.log('Initial date', date.toString());

var iterator = cron.parseExpression('45 * * * *', {currentDate:date})

for (var i=0; i < 10; i++) {
  console.log(iterator.next().toString())
}
```

**Comment by jrphub** [comment]
First of all thanks for your quick reply.

This prints 10 next execution time.

Actually, I want modified cron expression as per UTC.
For example :
45 * * *  w.r.t IST will be converted to 15 * * * * w.r.t GMT

**Comment by santigimeno** [comment]
OK. I understand now. No I don't think that's supported. Out of curiosity, what's your use case?

**Comment by jrphub** [comment]
okay, no problem.
Usecase is : 
from UI, user will set the cron expression as per his local timezone. The expression should be converted as per UTC and This new expression will be submitted to oozie from backend.

The reason of such requirement is explained in my previous reply

**Comment by harrisiirak** [comment]
@jrphub not sure if I understand your issue fully. The solution @santigimeno provided is quite like you should handle such case.

**Comment by santigimeno** [comment]
@harrisiirak I think their backend is not using `cron-parser` but uses the cron strings to schedule tasks. Also the date in their backend is configured as UTC, so they need to *translate*  the cron expressions from a valid expression in the local time, to the equivalent expression in UTC.

**Comment by jrphub** [comment]
@santigimeno yes, you are correct.

**Comment by santigimeno** [comment]
@jrphub I guess changing the backend is out of question, right?

I think at this moment, `cron-parser` can't help you , nor how difficult would be to create a *generic transalator** that worked on every case :(. It seems like an interesting project though.

**Comment by jrphub** [comment]
yes, changing backend (i.e. oozie) is not possible. Let me check what I can do. Anyways, Thanks for your help.

**Comment by harrisiirak** [comment]
Well yep, this is a bit out of this library scope.
I you want to play around and/or manipulate with local time then `faketime` (https://github.com/wolfcw/libfaketime)  is a interesting library that may help you.

**Comment by jrphub** [comment]
@harrisiirak Thanks I will check it.

**Comment by udit-pandey** [comment]
@jrphub were you able to get a solution for this?
