### ISSUE TITLE
iterator.next() is extremely slow

### ISSUE THREAD

**Issue by ffxsam** [harrisiirak/cron-parser#78]
I modified the example code to remove the current and end dates, as I want to have an iterator that will work indefinitely (see below).

```js
var options = {
  iterator: true
};
```

For some reason, when used this way, `.next()` is extremely slow. I added back in `currentDate` and `endDate`, and I noticed that the larger the gap between those two, the slower `.next()` was.

**Comment by harrisiirak** [comment]
@ffxsam can you paste the exact code that has slow behavior?

**Comment by ffxsam** [comment]
Never mind, I think I was misunderstanding how to use the parser. All is well!
