### ISSUE TITLE
toUTC() nonexistent

### ISSUE THREAD

**Issue by ffxsam** [harrisiirak/cron-parser#79]
In the README, there's this example:

```
  console.log('Date: ', interval.next().toUTC().toString());
```

But when I try it, I get an error:

``` js
const parser = require('cron-parser');

const interval = parser.parseExpression('*/20 * * * *');
console.log(interval.next().toUTC());
```

```
console.log(interval.next().toUTC());
                            ^

TypeError: interval.next(...).toUTC is not a function
```

**Comment by bcpxqz** [comment]
this's not exists toUTC method in "lib/date.js", use toISOString or toDate

**Comment by santigimeno** [comment]
@ffxsam `CronDate` is basically a wrapper over `moment.js` implementing part of the `Date` interface plus some helper functions. There are 2 options to fix this:
- Change the code in the README to not use `toUTC()`.
- Implement `toUTC()` in `CronDate`.

Both should be quite easy to fix :)

**Comment by harrisiirak** [comment]
Yep, documentation needs updating.
