### ISSUE TITLE
How to import into react native 

### ISSUE THREAD

**Issue by QuantumInformation** [harrisiirak/cron-parser#87]
I am trying this in a react native project:

`import  CronParser from 'cron-parser'`

but when running CronParser is undefined.

**Comment by harrisiirak** [comment]
@QuantumInformation did you try:

`import { parseExpression } from 'cron-parser';`

**Comment by QuantumInformation** [comment]
yep that worked thx!

**Comment by QuantumInformation** [comment]
Hmm, the issue started popping up again, I'm not sure if it's a pure RN thing now..

![image](https://cloud.githubusercontent.com/assets/216566/22108238/0af188e2-de4a-11e6-9ce6-267358a5d084.png)
