### ISSUE TITLE
Not incrementing interval

### ISSUE THREAD

**Issue by rfvallina** [harrisiirak/cron-parser#91]
I saw this should have been fixed in version 1.1.1, so I upgraded till latest version (2.3.1).

But still failing (and not in the second iteration, but in the first)

This is the source code:
```
var next; 

        try {
            next = cronParser.parseExpression(task.repeat)
                .next().toString();
            if(task.name == 'bidQueue'){
            	console.log("Repeat: " + task.repeat);
            	console.log("Now: " + new Date());
            	console.log("Next1: " + next);
            }
            next = new Date(next);
            if(task.name == 'bidQueue')
            	console.log("Next2: " + next);
        } catch (e) {
            console.error('Error setting up cron job (' + task.name +
                ').', e.message || e);
            return alias;
        }
```

And this is the output:

_Repeat: * * * * *
Now: Tue Feb 21 2017 16:45:00 GMT+0100 (CET)
Next1: Tue Feb 21 2017 16:45:00 GMT+0100
Next2: Tue Feb 21 2017 16:45:00 GMT+0100 (CET)_

As you see, Next1 and Next2 should have been incremented in 1 minute, but the time is the same as Now

**Comment by santigimeno** [comment]
@rfvallina can you check if https://github.com/harrisiirak/cron-parser/pull/93 fixes the issue?

**Comment by rfvallina** [comment]
Thank you.
I'll check and let you know
