### ISSUE TITLE
second/minute inconsistent behaviour

### ISSUE THREAD

**Issue by nrempel** [harrisiirak/cron-parser#92]
Hi there, I'm seeing inconsistent behaviour when schedule secondly vs minutely jobs.

```javascript
// lolex spoofs Date so the time stays put for this example.
var lolex = require('lolex');
lolex.install();
var parser = require('cron-parser');
var second = parser.parseExpression('* * * * * *');
var minute = parser.parseExpression('* * * * *');

second.next().toString()
// 'Wed Dec 31 1969 16:00:01 GMT-0800' <--- starts at **2nd** second (00:00:01)
second.next().toString()
// 'Wed Dec 31 1969 16:00:02 GMT-0800'

minute.next().toString()
// 'Wed Dec 31 1969 16:00:00 GMT-0800' <--- starts at **1st** minute (00:00:00)
minute.next().toString()
// 'Wed Dec 31 1969 16:01:00 GMT-0800'

```

This is super obscure but I ran into it when writing tests which made it apparent.

Unless I'm missing something. Is this a requirement somehow?

Thanks!

**Edit:**

I tracked down the problem. 

The minutely scheduler allows scheduling items in the past (it has a resolution of only 1 second). For example, I can set the epoch in my example to *one second less one millisecond* `lolex.install(999);`. In this case, `minute.next().toString()` will still output 'Wed Dec 31 1969 16:00:00 GMT-0800'. But, `second.next().toString()` will always return a date in the future.

**Comment by nrempel** [comment]
maybe related to https://github.com/harrisiirak/cron-parser/blob/master/lib/expression.js#L393

**Comment by santigimeno** [comment]
@nrempel can you check if https://github.com/harrisiirak/cron-parser/pull/93 fixes the issue?

**Comment by harrisiirak** [comment]
@santigimeno @nrempel are we good to merge the bugfix?

**Comment by santigimeno** [comment]
From my side I'm good with the change, it'd be better if we can confirm it fixes both related issues.

**Comment by nrempel** [comment]
Sorry, everyone I've been super busy and haven't had much time to look at my open source stuff.

I'll try to check sometime soon and check-in on this thread.

Thanks for all the work everyone!
