### ISSUE TITLE
Does the order of dayOfWeek field matters?

### ISSUE THREAD

**Issue by kqkq** [harrisiirak/cron-parser#95]
For the cron expression below:

`0 0 9 * * FRI,MON,SAT,SUN,THU,TUE,WED`

will only be triggered on Fri. and Sat. It seems the order of `dayOfWeek` field matters.

Is this an expected behavior or a bug?

**Comment by harrisiirak** [comment]
@kqkq not sure about the order. I see that we don't sort it at the moment: https://github.com/harrisiirak/cron-parser/blob/master/lib/expression.js#L224

As I understand when align weekdays correctly (from sun to sat) it works as expected?

**Comment by kqkq** [comment]
@harrisiirak Thanks for the reply. I think it works as expected when we align the weekdays in order.
