### ISSUE TITLE
next() and prev() are not symmetrical; prev() is skipping a day that next() includes. 

### ISSUE THREAD

**Issue by shaunluttin** [harrisiirak/cron-parser#96]
Expected Behavior

A call to `next()` is symmetrical with a call to `prev()`.

Actual Behavior

A call to `next()` produces `Sat` whereas a call to `prev()` skips `Sat` and instead produces `Fri`. 

```
var cronParser = require("cron-parser")

const options = {
    currentDate: new Date("Tue 03 Jan 2017 00:00:00 UTC"),
    utc: true
};
 
const interval = cronParser.parseExpression("0 30 15 * * 1-6", options);

console.log(interval.prev().toDate().toUTCString()); // Mon 
console.log(interval.prev().toDate().toUTCString()); // Fri
console.log(interval.next().toDate().toUTCString()); // Sat
console.log(interval.next().toDate().toUTCString()); // Mon
console.log(interval.prev().toDate().toUTCString()); // Fri
```

https://runkit.com/5912594388e92a00122cb663/5912594388e92a00122cb664

**Comment by harrisiirak** [comment]
@faazshift can you look into that? Looks suspicious.

**Comment by shaunluttin** [comment]
@faazshift @harrisiirak Please ping me if you would like help on this.

**Comment by santigimeno** [comment]
@shaunluttin cannot reproduce the error with current master. I get this output, which looks fine.
```
Mon, 02 Jan 2017 15:30:00 GMT
Sat, 31 Dec 2016 15:30:00 GMT
Tue, 03 Jan 2017 15:30:00 GMT
Wed, 04 Jan 2017 15:30:00 GMT
Tue, 03 Jan 2017 15:30:00 GMT
```

**Comment by faazshift** [comment]
@harrisiirak @santigimeno I've meant to work on this, but life has been pretty hectic. To me this bug still seems to exist, both on master and on #99. I'll try to dig into this sometime this week.

**Comment by shaunluttin** [comment]
We've unfortunately moved on to another library. Apologies for not being more helpful.

**Comment by harrisiirak** [comment]
@santigimeno @faazshift @shaunluttin looks like the `utc: true` is root of the evil here.

Anyhow, running this:

```js
const options = {
    currentDate: new Date("Tue 03 Jan 2017 00:00:00 UTC")
};
 
const interval = parser.parseExpression("0 30 15 * * 1-6", options);

console.log(interval.prev().toDate().toUTCString());
console.log(interval.prev().toDate().toUTCString());
console.log(interval.next().toDate().toUTCString());
console.log(interval.next().toDate().toUTCString());
console.log(interval.prev().toDate().toUTCString());
```

Output:

```
Mon, 02 Jan 2017 13:30:00 GMT
Sat, 31 Dec 2016 13:30:00 GMT
Mon, 02 Jan 2017 13:30:00 GMT
Tue, 03 Jan 2017 13:30:00 GMT
Mon, 02 Jan 2017 13:30:00 GMT
```

Looks good to me.

**Comment by santigimeno** [comment]
I think https://github.com/harrisiirak/cron-parser/pull/101 should fix this.

**Comment by faazshift** [comment]
@santigimeno @harrisiirak According to the test script I made while attempting to debug this issue, #101 does fix the issue.
